---
queue_rules:
  - name: default
    conditions:
      - check-success~=^Test Java
      - check-success=docs/readthedocs.org:crate-jdbc
      - check-success=verification/cla-signed

pull_request_rules:
  - name: automatic merge
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=^Test Java
      - status-success=docs/readthedocs.org:crate-jdbc
      - status-success=verification/cla-signed
    actions:
      queue:
        method: rebase
        name: default
