// https://github.com/raydac/java-comment-preprocessor

def srcRoot = 'upstream/pgjdbc/src/main'
def jcpRoot = "${buildDir}/jcp"

configurations {
    jcp
}

dependencies {
    implementation 'com.github.waffle:waffle-jna:1.9.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    implementation 'com.ongres.scram:scram-client:3.2'
    compileOnly 'org.checkerframework:checker-qual:3.55.1'
    jcp('com.igormaznitsa:jcp:6.0.1') {
        exclude group: 'org.apache.maven.*'
        exclude group: 'org.codehaus.*'
    }
}

task preprocessVersion {
    inputs.dir "${srcRoot}/version"
    inputs.file 'version.properties'
    outputs.dir "${jcpRoot}/version"
    doLast {
        def jcpjar = file(project.configurations.jcp.find { it.name.startsWith("jcp-") })
        ant.taskdef(resource: 'com/igormaznitsa/jcp/ant/antlib.xml', classpath: jcpjar)
        ant.preprocess(excluded: "none", processing: 'java', source: "${srcRoot}/version", destination: "${jcpRoot}/version") {
            cfgFile(file: 'version.properties')
        }
    }
}

sourceSets {
    main {
        java {
            srcDir "${srcRoot}/java"
            srcDir "${jcpRoot}/version"
            exclude '**/osgi/*'
        }
        resources {
            srcDir "${srcRoot}/resources"
            exclude '**/services/java.sql.Driver'
        }
    }
}

compileJava.dependsOn preprocessVersion

test {
    enabled = false;
}
