import java.lang.reflect.GenericArrayType;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.lang.reflect.TypeVariable;
import java.lang.reflect.WildcardType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.stream.Collectors;

/**
 * Emits the Forwarding* delegate base classes in
 * driver/main/java/io/crate/client/jdbc/: one abstract class per wrapped
 * java.sql interface, forwarding every method to a delegate instance.
 * Behavioral overrides live in the hand-written Crate* subclasses, so the
 * generated files carry no logic and can be regenerated wholesale whenever
 * a newer JDBC spec adds methods:
 *
 *   java devtools/GenerateForwarding.java
 */
public class GenerateForwarding {

    private static final Class<?>[] INTERFACES = {
        java.sql.Connection.class,
        java.sql.Statement.class,
        java.sql.PreparedStatement.class,
        java.sql.ResultSet.class,
        java.sql.DatabaseMetaData.class,
    };

    /**
     * Methods present in the generating JDK's java.sql but absent from the
     * Java 11 API this project compiles against (--release 11). Keyed as
     * "InterfaceSimpleName#methodName".
     */
    private static final java.util.Set<String> NOT_IN_RELEASE_11 = java.util.Set.of(
        "Connection#enquoteIdentifier",
        "Connection#enquoteLiteral",
        "Connection#enquoteNCharLiteral",
        "Connection#isSimpleIdentifier"
    );

    public static void main(String[] args) throws Exception {
        Path outDir = Path.of("driver/main/java/io/crate/client/jdbc");
        Files.createDirectories(outDir);
        for (Class<?> iface : INTERFACES) {
            String className = "Forwarding" + iface.getSimpleName();
            Files.writeString(outDir.resolve(className + ".java"), render(iface, className));
            System.out.println("wrote " + outDir.resolve(className + ".java"));
        }
    }

    private static String render(Class<?> iface, String className) {
        StringBuilder sb = new StringBuilder();
        sb.append("/*\n")
          .append(" * Licensed to Crate under one or more contributor license agreements.\n")
          .append(" * See the NOTICE file distributed with this work for additional\n")
          .append(" * information regarding copyright ownership.  Crate licenses this file\n")
          .append(" * to you under the Apache License, Version 2.0 (the \"License\"); you may\n")
          .append(" * not use this file except in compliance with the License.  You may\n")
          .append(" * obtain a copy of the License at\n")
          .append(" *\n")
          .append(" *     http://www.apache.org/licenses/LICENSE-2.0\n")
          .append(" *\n")
          .append(" * Unless required by applicable law or agreed to in writing, software\n")
          .append(" * distributed under the License is distributed on an \"AS IS\" BASIS,\n")
          .append(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n")
          .append(" * implied.  See the License for the specific language governing\n")
          .append(" * permissions and limitations under the License.\n")
          .append(" */\n\n")
          .append("package io.crate.client.jdbc;\n\n")
          .append("import ").append(iface.getName()).append(";\n\n")
          .append("/**\n")
          .append(" * Forwards every {@link ").append(iface.getSimpleName()).append("} method to a delegate.\n")
          .append(" * Generated by devtools/GenerateForwarding.java — do not edit by hand.\n")
          .append(" */\n")
          .append("public abstract class ").append(className)
          .append(" implements ").append(iface.getSimpleName()).append(" {\n\n")
          .append("    protected final ").append(iface.getSimpleName()).append(" delegate;\n\n")
          .append("    protected ").append(className).append("(")
          .append(iface.getSimpleName()).append(" delegate) {\n")
          .append("        this.delegate = delegate;\n")
          .append("    }\n");

        Map<String, Method> methods = new LinkedHashMap<>();
        for (Method m : iface.getMethods()) {
            if (Modifier.isStatic(m.getModifiers())) {
                continue;
            }
            if (NOT_IN_RELEASE_11.contains(iface.getSimpleName() + "#" + m.getName())) {
                continue;
            }
            String key = m.getName() + java.util.Arrays.stream(m.getParameterTypes())
                .map(Class::getName).collect(Collectors.joining(","));
            methods.putIfAbsent(key, m);
        }
        List<Method> sorted = new ArrayList<>(methods.values());
        sorted.sort(Comparator.comparing(Method::getName)
            .thenComparing(m -> m.getParameterCount())
            .thenComparing(Method::toString));

        for (Method m : sorted) {
            sb.append("\n    @Override\n    public ");
            TypeVariable<?>[] typeParams = m.getTypeParameters();
            if (typeParams.length > 0) {
                StringJoiner tj = new StringJoiner(", ", "<", "> ");
                for (TypeVariable<?> tv : typeParams) {
                    tj.add(tv.getName());
                }
                sb.append(tj);
            }
            sb.append(typeName(m.getGenericReturnType())).append(" ").append(m.getName()).append("(");
            Type[] params = m.getGenericParameterTypes();
            StringJoiner pj = new StringJoiner(", ");
            for (int i = 0; i < params.length; i++) {
                pj.add(typeName(params[i]) + " p" + i);
            }
            sb.append(pj).append(")");
            Type[] exceptions = m.getGenericExceptionTypes();
            if (exceptions.length > 0) {
                StringJoiner ej = new StringJoiner(", ", " throws ", "");
                for (Type e : exceptions) {
                    ej.add(typeName(e));
                }
                sb.append(ej);
            }
            sb.append(" {\n        ");
            if (m.getReturnType() != void.class) {
                sb.append("return ");
            }
            sb.append("delegate.").append(m.getName()).append("(");
            StringJoiner aj = new StringJoiner(", ");
            for (int i = 0; i < params.length; i++) {
                aj.add("p" + i);
            }
            sb.append(aj).append(");\n    }\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private static String typeName(Type type) {
        if (type instanceof Class<?> cls) {
            return cls.getCanonicalName();
        }
        if (type instanceof ParameterizedType pt) {
            StringJoiner tj = new StringJoiner(", ", "<", ">");
            for (Type arg : pt.getActualTypeArguments()) {
                tj.add(typeName(arg));
            }
            return typeName(pt.getRawType()) + tj;
        }
        if (type instanceof GenericArrayType gat) {
            return typeName(gat.getGenericComponentType()) + "[]";
        }
        if (type instanceof TypeVariable<?> tv) {
            return tv.getName();
        }
        if (type instanceof WildcardType wt) {
            Type[] upper = wt.getUpperBounds();
            Type[] lower = wt.getLowerBounds();
            if (lower.length > 0) {
                return "? super " + typeName(lower[0]);
            }
            if (upper.length == 1 && upper[0] == Object.class) {
                return "?";
            }
            return "? extends " + typeName(upper[0]);
        }
        throw new IllegalArgumentException("Cannot render type: " + type);
    }
}
