/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import org.postgresql.PGStatement;
import org.postgresql.util.PSQLException;
import org.postgresql.util.PSQLState;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Hands out {@link CrateResultSet}s, keeps statements attached to their owning
 * {@link CrateConnection}, and bounds every execution by the statement's query
 * timeout as described in {@link CrateQueryTimeout}.
 *
 * <p>Prepared statements and calls build on this, so an execution started
 * through any of them is bounded the same way and its rows come back through
 * the same wrapper.</p>
 */
@SuppressWarnings("deprecation")
public class CrateStatement implements Statement, PGStatement {

    protected final Statement delegate;
    protected final PGStatement pgDelegate;

    private final CrateConnection connection;
    private final CurrentResultSet results = new CurrentResultSet(this);
    private final CurrentResultSet generatedKeys = new CurrentResultSet(this);

    CrateStatement(Statement delegate, CrateConnection connection) throws SQLException {
        this.delegate = delegate;
        this.pgDelegate = delegate.unwrap(PGStatement.class);
        this.connection = connection;
    }

    /**
     * Holds this statement's query timeout for the length of one execution.
     * Every method that runs something on the server brackets it with this.
     */
    protected CrateQueryTimeout bounded() throws SQLException {
        return connection.appliedQueryTimeout(getQueryTimeout());
    }

    /** The wrapper for the rows an execution produced. */
    protected CrateResultSet resultSet(ResultSet resultSet) {
        return results.of(resultSet);
    }

    /**
     * The rows are taken inside the bracket and wrapped outside it, so that
     * what the wrapper is built around is a result set the server has already
     * handed over. Giving the timeout back can fail, and that failure is the
     * one a caller hears about; the rows it was raised over are still the
     * statement's, reachable through {@link #getResultSet()}.
     */
    @Adapted
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ResultSet rows;
        try (CrateQueryTimeout bound = bounded()) {
            rows = delegate.executeQuery(sql);
        }
        return resultSet(rows);
    }

    @Adapted
    @Override
    public boolean execute(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql);
        }
    }

    @Adapted
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, autoGeneratedKeys);
        }
    }

    @Adapted
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, columnIndexes);
        }
    }

    @Adapted
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, columnNames);
        }
    }

    @Adapted
    @Override
    public int executeUpdate(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql);
        }
    }

    @Adapted
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, autoGeneratedKeys);
        }
    }

    @Adapted
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, columnIndexes);
        }
    }

    @Adapted
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, columnNames);
        }
    }

    @Adapted
    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql);
        }
    }

    @Adapted
    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, autoGeneratedKeys);
        }
    }

    @Adapted
    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, columnIndexes);
        }
    }

    @Adapted
    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, columnNames);
        }
    }

    @Adapted
    @Override
    public int[] executeBatch() throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeBatch();
        }
    }

    @Adapted
    @Override
    public long[] executeLargeBatch() throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeBatch();
        }
    }

    @Adapted
    @Override
    public ResultSet getResultSet() throws SQLException {
        return resultSet(delegate.getResultSet());
    }

    @Adapted
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return generatedKeys.of(delegate.getGeneratedKeys());
    }

    @Adapted
    @Override
    public CrateConnection getConnection() throws SQLException {
        // A closed statement has no connection to hand out, which is the one
        // thing the wrapper has to check for itself: the answer is held here
        // rather than asked of the delegate.
        if (delegate.isClosed()) {
            throw new PSQLException("This statement has been closed.",
                PSQLState.OBJECT_NOT_IN_STATE);
        }
        return connection;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return iface.isInstance(this) ? iface.cast(this) : delegate.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this) || delegate.isWrapperFor(iface);
    }

    // <editor-fold defaultstate="collapsed" desc="Delegation to pgJDBC (43 methods)">

    @Override
    public void addBatch(String p0) throws SQLException {
        delegate.addBatch(p0);
    }

    @Override
    public void cancel() throws SQLException {
        delegate.cancel();
    }

    @Override
    public void clearBatch() throws SQLException {
        delegate.clearBatch();
    }

    @Override
    public void clearWarnings() throws SQLException {
        delegate.clearWarnings();
    }

    @Override
    public void close() throws SQLException {
        delegate.close();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        delegate.closeOnCompletion();
    }

    @Override
    public String enquoteIdentifier(String p0, boolean p1) throws SQLException {
        return delegate.enquoteIdentifier(p0, p1);
    }

    @Override
    public String enquoteLiteral(String p0) throws SQLException {
        return delegate.enquoteLiteral(p0);
    }

    @Override
    public String enquoteNCharLiteral(String p0) throws SQLException {
        return delegate.enquoteNCharLiteral(p0);
    }

    @Override
    public boolean getAdaptiveFetch() {
        return pgDelegate.getAdaptiveFetch();
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return delegate.getFetchDirection();
    }

    @Override
    public int getFetchSize() throws SQLException {
        return delegate.getFetchSize();
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        return delegate.getLargeMaxRows();
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return delegate.getLargeUpdateCount();
    }

    @Override
    public long getLastOID() throws SQLException {
        return pgDelegate.getLastOID();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return delegate.getMaxFieldSize();
    }

    @Override
    public int getMaxRows() throws SQLException {
        return delegate.getMaxRows();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return delegate.getMoreResults();
    }

    @Override
    public boolean getMoreResults(int p0) throws SQLException {
        return delegate.getMoreResults(p0);
    }

    @Override
    public int getPrepareThreshold() {
        return pgDelegate.getPrepareThreshold();
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return delegate.getQueryTimeout();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return delegate.getResultSetConcurrency();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return delegate.getResultSetHoldability();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return delegate.getResultSetType();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return delegate.getUpdateCount();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return delegate.getWarnings();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return delegate.isCloseOnCompletion();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return delegate.isClosed();
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return delegate.isPoolable();
    }

    @Override
    public boolean isSimpleIdentifier(String p0) throws SQLException {
        return delegate.isSimpleIdentifier(p0);
    }

    @Override
    public boolean isUseServerPrepare() {
        return pgDelegate.isUseServerPrepare();
    }

    @Override
    public void setAdaptiveFetch(boolean adaptiveFetch) {
        pgDelegate.setAdaptiveFetch(adaptiveFetch);
    }

    @Override
    public void setCursorName(String p0) throws SQLException {
        delegate.setCursorName(p0);
    }

    @Override
    public void setEscapeProcessing(boolean p0) throws SQLException {
        delegate.setEscapeProcessing(p0);
    }

    @Override
    public void setFetchDirection(int p0) throws SQLException {
        delegate.setFetchDirection(p0);
    }

    @Override
    public void setFetchSize(int p0) throws SQLException {
        delegate.setFetchSize(p0);
    }

    @Override
    public void setLargeMaxRows(long p0) throws SQLException {
        delegate.setLargeMaxRows(p0);
    }

    @Override
    public void setMaxFieldSize(int p0) throws SQLException {
        delegate.setMaxFieldSize(p0);
    }

    @Override
    public void setMaxRows(int p0) throws SQLException {
        delegate.setMaxRows(p0);
    }

    @Override
    public void setPoolable(boolean p0) throws SQLException {
        delegate.setPoolable(p0);
    }

    @Override
    public void setPrepareThreshold(int threshold) throws SQLException {
        pgDelegate.setPrepareThreshold(threshold);
    }

    @Override
    public void setQueryTimeout(int p0) throws SQLException {
        delegate.setQueryTimeout(p0);
    }

    @Override
    public void setUseServerPrepare(boolean flag) throws SQLException {
        pgDelegate.setUseServerPrepare(flag);
    }
    // </editor-fold>
}
