/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import org.postgresql.util.PSQLException;
import org.postgresql.util.PSQLState;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Hands out {@link CrateResultSet}s, keeps statements attached to their owning
 * {@link CrateConnection}, and bounds every execution by the statement's query
 * timeout as described in {@link CrateQueryTimeout}.
 *
 * <p>Prepared statements and calls build on this, so an execution started
 * through any of them is bounded the same way and its rows come back through
 * the same wrapper.</p>
 */
public class CrateStatement extends ForwardingStatement {

    private final CrateConnection connection;
    private final CurrentResultSet results = new CurrentResultSet(this);
    private final CurrentResultSet generatedKeys = new CurrentResultSet(this);

    CrateStatement(Statement delegate, CrateConnection connection) throws SQLException {
        super(delegate);
        this.connection = connection;
    }

    /**
     * Holds this statement's query timeout for the length of one execution.
     * Every method that runs something on the server brackets it with this.
     */
    protected CrateQueryTimeout bounded() throws SQLException {
        return connection.appliedQueryTimeout(getQueryTimeout());
    }

    /** The wrapper for the rows an execution produced. */
    protected CrateResultSet resultSet(ResultSet resultSet) {
        return results.of(resultSet);
    }

    /**
     * The rows are taken inside the bracket and wrapped outside it, so that
     * what the wrapper is built around is a result set the server has already
     * handed over. Giving the timeout back can fail, and that failure is the
     * one a caller hears about; the rows it was raised over are still the
     * statement's, reachable through {@link #getResultSet()}.
     */
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ResultSet rows;
        try (CrateQueryTimeout bound = bounded()) {
            rows = delegate.executeQuery(sql);
        }
        return resultSet(rows);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql);
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, autoGeneratedKeys);
        }
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, columnIndexes);
        }
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.execute(sql, columnNames);
        }
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql);
        }
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, autoGeneratedKeys);
        }
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, columnIndexes);
        }
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeUpdate(sql, columnNames);
        }
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql);
        }
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, autoGeneratedKeys);
        }
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, columnIndexes);
        }
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeUpdate(sql, columnNames);
        }
    }

    @Override
    public int[] executeBatch() throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeBatch();
        }
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        try (CrateQueryTimeout bound = bounded()) {
            return delegate.executeLargeBatch();
        }
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return resultSet(delegate.getResultSet());
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return generatedKeys.of(delegate.getGeneratedKeys());
    }

    @Override
    public CrateConnection getConnection() throws SQLException {
        // A closed statement has no connection to hand out, which is the one
        // thing the wrapper has to check for itself: the answer is held here
        // rather than asked of the delegate.
        if (delegate.isClosed()) {
            throw new PSQLException("This statement has been closed.",
                PSQLState.OBJECT_NOT_IN_STATE);
        }
        return connection;
    }
}
