/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 */

package io.crate.client.jdbc;

import java.sql.ParameterMetaData;

/**
 * Forwards every {@link ParameterMetaData} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingParameterMetaData implements ParameterMetaData {

    protected final ParameterMetaData delegate;

    protected ForwardingParameterMetaData(ParameterMetaData delegate) {
        this.delegate = delegate;
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public java.lang.String getParameterClassName(int p0) throws java.sql.SQLException {
        return delegate.getParameterClassName(p0);
    }

    @Override
    public int getParameterCount() throws java.sql.SQLException {
        return delegate.getParameterCount();
    }

    @Override
    public int getParameterMode(int p0) throws java.sql.SQLException {
        return delegate.getParameterMode(p0);
    }

    @Override
    public int getParameterType(int p0) throws java.sql.SQLException {
        return delegate.getParameterType(p0);
    }

    @Override
    public java.lang.String getParameterTypeName(int p0) throws java.sql.SQLException {
        return delegate.getParameterTypeName(p0);
    }

    @Override
    public int getPrecision(int p0) throws java.sql.SQLException {
        return delegate.getPrecision(p0);
    }

    @Override
    public int getScale(int p0) throws java.sql.SQLException {
        return delegate.getScale(p0);
    }

    @Override
    public int isNullable(int p0) throws java.sql.SQLException {
        return delegate.isNullable(p0);
    }

    @Override
    public boolean isSigned(int p0) throws java.sql.SQLException {
        return delegate.isSigned(p0);
    }
}
