/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 */

package io.crate.client.jdbc;

import java.sql.DatabaseMetaData;

/**
 * Forwards every {@link DatabaseMetaData} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingDatabaseMetaData implements DatabaseMetaData {

    protected final DatabaseMetaData delegate;

    protected ForwardingDatabaseMetaData(DatabaseMetaData delegate) {
        this.delegate = delegate;
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public boolean allProceduresAreCallable() throws java.sql.SQLException {
        return delegate.allProceduresAreCallable();
    }

    @Override
    public boolean allTablesAreSelectable() throws java.sql.SQLException {
        return delegate.allTablesAreSelectable();
    }

    @Override
    public boolean autoCommitFailureClosesAllResultSets() throws java.sql.SQLException {
        return delegate.autoCommitFailureClosesAllResultSets();
    }

    @Override
    public boolean dataDefinitionCausesTransactionCommit() throws java.sql.SQLException {
        return delegate.dataDefinitionCausesTransactionCommit();
    }

    @Override
    public boolean dataDefinitionIgnoredInTransactions() throws java.sql.SQLException {
        return delegate.dataDefinitionIgnoredInTransactions();
    }

    @Override
    public boolean deletesAreDetected(int p0) throws java.sql.SQLException {
        return delegate.deletesAreDetected(p0);
    }

    @Override
    public boolean doesMaxRowSizeIncludeBlobs() throws java.sql.SQLException {
        return delegate.doesMaxRowSizeIncludeBlobs();
    }

    @Override
    public boolean generatedKeyAlwaysReturned() throws java.sql.SQLException {
        return delegate.generatedKeyAlwaysReturned();
    }

    @Override
    public java.sql.ResultSet getAttributes(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getAttributes(p0, p1, p2, p3);
    }

    @Override
    public java.sql.ResultSet getBestRowIdentifier(java.lang.String p0, java.lang.String p1, java.lang.String p2, int p3, boolean p4) throws java.sql.SQLException {
        return delegate.getBestRowIdentifier(p0, p1, p2, p3, p4);
    }

    @Override
    public java.lang.String getCatalogSeparator() throws java.sql.SQLException {
        return delegate.getCatalogSeparator();
    }

    @Override
    public java.lang.String getCatalogTerm() throws java.sql.SQLException {
        return delegate.getCatalogTerm();
    }

    @Override
    public java.sql.ResultSet getCatalogs() throws java.sql.SQLException {
        return delegate.getCatalogs();
    }

    @Override
    public java.sql.ResultSet getClientInfoProperties() throws java.sql.SQLException {
        return delegate.getClientInfoProperties();
    }

    @Override
    public java.sql.ResultSet getColumnPrivileges(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getColumnPrivileges(p0, p1, p2, p3);
    }

    @Override
    public java.sql.ResultSet getColumns(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getColumns(p0, p1, p2, p3);
    }

    @Override
    public java.sql.Connection getConnection() throws java.sql.SQLException {
        return delegate.getConnection();
    }

    @Override
    public java.sql.ResultSet getCrossReference(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, java.lang.String p4, java.lang.String p5) throws java.sql.SQLException {
        return delegate.getCrossReference(p0, p1, p2, p3, p4, p5);
    }

    @Override
    public int getDatabaseMajorVersion() throws java.sql.SQLException {
        return delegate.getDatabaseMajorVersion();
    }

    @Override
    public int getDatabaseMinorVersion() throws java.sql.SQLException {
        return delegate.getDatabaseMinorVersion();
    }

    @Override
    public java.lang.String getDatabaseProductName() throws java.sql.SQLException {
        return delegate.getDatabaseProductName();
    }

    @Override
    public java.lang.String getDatabaseProductVersion() throws java.sql.SQLException {
        return delegate.getDatabaseProductVersion();
    }

    @Override
    public int getDefaultTransactionIsolation() throws java.sql.SQLException {
        return delegate.getDefaultTransactionIsolation();
    }

    @Override
    public int getDriverMajorVersion() {
        return delegate.getDriverMajorVersion();
    }

    @Override
    public int getDriverMinorVersion() {
        return delegate.getDriverMinorVersion();
    }

    @Override
    public java.lang.String getDriverName() throws java.sql.SQLException {
        return delegate.getDriverName();
    }

    @Override
    public java.lang.String getDriverVersion() throws java.sql.SQLException {
        return delegate.getDriverVersion();
    }

    @Override
    public java.sql.ResultSet getExportedKeys(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getExportedKeys(p0, p1, p2);
    }

    @Override
    public java.lang.String getExtraNameCharacters() throws java.sql.SQLException {
        return delegate.getExtraNameCharacters();
    }

    @Override
    public java.sql.ResultSet getFunctionColumns(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getFunctionColumns(p0, p1, p2, p3);
    }

    @Override
    public java.sql.ResultSet getFunctions(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getFunctions(p0, p1, p2);
    }

    @Override
    public java.lang.String getIdentifierQuoteString() throws java.sql.SQLException {
        return delegate.getIdentifierQuoteString();
    }

    @Override
    public java.sql.ResultSet getImportedKeys(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getImportedKeys(p0, p1, p2);
    }

    @Override
    public java.sql.ResultSet getIndexInfo(java.lang.String p0, java.lang.String p1, java.lang.String p2, boolean p3, boolean p4) throws java.sql.SQLException {
        return delegate.getIndexInfo(p0, p1, p2, p3, p4);
    }

    @Override
    public int getJDBCMajorVersion() throws java.sql.SQLException {
        return delegate.getJDBCMajorVersion();
    }

    @Override
    public int getJDBCMinorVersion() throws java.sql.SQLException {
        return delegate.getJDBCMinorVersion();
    }

    @Override
    public int getMaxBinaryLiteralLength() throws java.sql.SQLException {
        return delegate.getMaxBinaryLiteralLength();
    }

    @Override
    public int getMaxCatalogNameLength() throws java.sql.SQLException {
        return delegate.getMaxCatalogNameLength();
    }

    @Override
    public int getMaxCharLiteralLength() throws java.sql.SQLException {
        return delegate.getMaxCharLiteralLength();
    }

    @Override
    public int getMaxColumnNameLength() throws java.sql.SQLException {
        return delegate.getMaxColumnNameLength();
    }

    @Override
    public int getMaxColumnsInGroupBy() throws java.sql.SQLException {
        return delegate.getMaxColumnsInGroupBy();
    }

    @Override
    public int getMaxColumnsInIndex() throws java.sql.SQLException {
        return delegate.getMaxColumnsInIndex();
    }

    @Override
    public int getMaxColumnsInOrderBy() throws java.sql.SQLException {
        return delegate.getMaxColumnsInOrderBy();
    }

    @Override
    public int getMaxColumnsInSelect() throws java.sql.SQLException {
        return delegate.getMaxColumnsInSelect();
    }

    @Override
    public int getMaxColumnsInTable() throws java.sql.SQLException {
        return delegate.getMaxColumnsInTable();
    }

    @Override
    public int getMaxConnections() throws java.sql.SQLException {
        return delegate.getMaxConnections();
    }

    @Override
    public int getMaxCursorNameLength() throws java.sql.SQLException {
        return delegate.getMaxCursorNameLength();
    }

    @Override
    public int getMaxIndexLength() throws java.sql.SQLException {
        return delegate.getMaxIndexLength();
    }

    @Override
    public long getMaxLogicalLobSize() throws java.sql.SQLException {
        return delegate.getMaxLogicalLobSize();
    }

    @Override
    public int getMaxProcedureNameLength() throws java.sql.SQLException {
        return delegate.getMaxProcedureNameLength();
    }

    @Override
    public int getMaxRowSize() throws java.sql.SQLException {
        return delegate.getMaxRowSize();
    }

    @Override
    public int getMaxSchemaNameLength() throws java.sql.SQLException {
        return delegate.getMaxSchemaNameLength();
    }

    @Override
    public int getMaxStatementLength() throws java.sql.SQLException {
        return delegate.getMaxStatementLength();
    }

    @Override
    public int getMaxStatements() throws java.sql.SQLException {
        return delegate.getMaxStatements();
    }

    @Override
    public int getMaxTableNameLength() throws java.sql.SQLException {
        return delegate.getMaxTableNameLength();
    }

    @Override
    public int getMaxTablesInSelect() throws java.sql.SQLException {
        return delegate.getMaxTablesInSelect();
    }

    @Override
    public int getMaxUserNameLength() throws java.sql.SQLException {
        return delegate.getMaxUserNameLength();
    }

    @Override
    public java.lang.String getNumericFunctions() throws java.sql.SQLException {
        return delegate.getNumericFunctions();
    }

    @Override
    public java.sql.ResultSet getPrimaryKeys(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getPrimaryKeys(p0, p1, p2);
    }

    @Override
    public java.sql.ResultSet getProcedureColumns(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getProcedureColumns(p0, p1, p2, p3);
    }

    @Override
    public java.lang.String getProcedureTerm() throws java.sql.SQLException {
        return delegate.getProcedureTerm();
    }

    @Override
    public java.sql.ResultSet getProcedures(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getProcedures(p0, p1, p2);
    }

    @Override
    public java.sql.ResultSet getPseudoColumns(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) throws java.sql.SQLException {
        return delegate.getPseudoColumns(p0, p1, p2, p3);
    }

    @Override
    public int getResultSetHoldability() throws java.sql.SQLException {
        return delegate.getResultSetHoldability();
    }

    @Override
    public java.sql.RowIdLifetime getRowIdLifetime() throws java.sql.SQLException {
        return delegate.getRowIdLifetime();
    }

    @Override
    public java.lang.String getSQLKeywords() throws java.sql.SQLException {
        return delegate.getSQLKeywords();
    }

    @Override
    public int getSQLStateType() throws java.sql.SQLException {
        return delegate.getSQLStateType();
    }

    @Override
    public java.lang.String getSchemaTerm() throws java.sql.SQLException {
        return delegate.getSchemaTerm();
    }

    @Override
    public java.sql.ResultSet getSchemas() throws java.sql.SQLException {
        return delegate.getSchemas();
    }

    @Override
    public java.sql.ResultSet getSchemas(java.lang.String p0, java.lang.String p1) throws java.sql.SQLException {
        return delegate.getSchemas(p0, p1);
    }

    @Override
    public java.lang.String getSearchStringEscape() throws java.sql.SQLException {
        return delegate.getSearchStringEscape();
    }

    @Override
    public java.lang.String getStringFunctions() throws java.sql.SQLException {
        return delegate.getStringFunctions();
    }

    @Override
    public java.sql.ResultSet getSuperTables(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getSuperTables(p0, p1, p2);
    }

    @Override
    public java.sql.ResultSet getSuperTypes(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getSuperTypes(p0, p1, p2);
    }

    @Override
    public java.lang.String getSystemFunctions() throws java.sql.SQLException {
        return delegate.getSystemFunctions();
    }

    @Override
    public java.sql.ResultSet getTablePrivileges(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getTablePrivileges(p0, p1, p2);
    }

    @Override
    public java.sql.ResultSet getTableTypes() throws java.sql.SQLException {
        return delegate.getTableTypes();
    }

    @Override
    public java.sql.ResultSet getTables(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String[] p3) throws java.sql.SQLException {
        return delegate.getTables(p0, p1, p2, p3);
    }

    @Override
    public java.lang.String getTimeDateFunctions() throws java.sql.SQLException {
        return delegate.getTimeDateFunctions();
    }

    @Override
    public java.sql.ResultSet getTypeInfo() throws java.sql.SQLException {
        return delegate.getTypeInfo();
    }

    @Override
    public java.sql.ResultSet getUDTs(java.lang.String p0, java.lang.String p1, java.lang.String p2, int[] p3) throws java.sql.SQLException {
        return delegate.getUDTs(p0, p1, p2, p3);
    }

    @Override
    public java.lang.String getURL() throws java.sql.SQLException {
        return delegate.getURL();
    }

    @Override
    public java.lang.String getUserName() throws java.sql.SQLException {
        return delegate.getUserName();
    }

    @Override
    public java.sql.ResultSet getVersionColumns(java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
        return delegate.getVersionColumns(p0, p1, p2);
    }

    @Override
    public boolean insertsAreDetected(int p0) throws java.sql.SQLException {
        return delegate.insertsAreDetected(p0);
    }

    @Override
    public boolean isCatalogAtStart() throws java.sql.SQLException {
        return delegate.isCatalogAtStart();
    }

    @Override
    public boolean isReadOnly() throws java.sql.SQLException {
        return delegate.isReadOnly();
    }

    @Override
    public boolean locatorsUpdateCopy() throws java.sql.SQLException {
        return delegate.locatorsUpdateCopy();
    }

    @Override
    public boolean nullPlusNonNullIsNull() throws java.sql.SQLException {
        return delegate.nullPlusNonNullIsNull();
    }

    @Override
    public boolean nullsAreSortedAtEnd() throws java.sql.SQLException {
        return delegate.nullsAreSortedAtEnd();
    }

    @Override
    public boolean nullsAreSortedAtStart() throws java.sql.SQLException {
        return delegate.nullsAreSortedAtStart();
    }

    @Override
    public boolean nullsAreSortedHigh() throws java.sql.SQLException {
        return delegate.nullsAreSortedHigh();
    }

    @Override
    public boolean nullsAreSortedLow() throws java.sql.SQLException {
        return delegate.nullsAreSortedLow();
    }

    @Override
    public boolean othersDeletesAreVisible(int p0) throws java.sql.SQLException {
        return delegate.othersDeletesAreVisible(p0);
    }

    @Override
    public boolean othersInsertsAreVisible(int p0) throws java.sql.SQLException {
        return delegate.othersInsertsAreVisible(p0);
    }

    @Override
    public boolean othersUpdatesAreVisible(int p0) throws java.sql.SQLException {
        return delegate.othersUpdatesAreVisible(p0);
    }

    @Override
    public boolean ownDeletesAreVisible(int p0) throws java.sql.SQLException {
        return delegate.ownDeletesAreVisible(p0);
    }

    @Override
    public boolean ownInsertsAreVisible(int p0) throws java.sql.SQLException {
        return delegate.ownInsertsAreVisible(p0);
    }

    @Override
    public boolean ownUpdatesAreVisible(int p0) throws java.sql.SQLException {
        return delegate.ownUpdatesAreVisible(p0);
    }

    @Override
    public boolean storesLowerCaseIdentifiers() throws java.sql.SQLException {
        return delegate.storesLowerCaseIdentifiers();
    }

    @Override
    public boolean storesLowerCaseQuotedIdentifiers() throws java.sql.SQLException {
        return delegate.storesLowerCaseQuotedIdentifiers();
    }

    @Override
    public boolean storesMixedCaseIdentifiers() throws java.sql.SQLException {
        return delegate.storesMixedCaseIdentifiers();
    }

    @Override
    public boolean storesMixedCaseQuotedIdentifiers() throws java.sql.SQLException {
        return delegate.storesMixedCaseQuotedIdentifiers();
    }

    @Override
    public boolean storesUpperCaseIdentifiers() throws java.sql.SQLException {
        return delegate.storesUpperCaseIdentifiers();
    }

    @Override
    public boolean storesUpperCaseQuotedIdentifiers() throws java.sql.SQLException {
        return delegate.storesUpperCaseQuotedIdentifiers();
    }

    @Override
    public boolean supportsANSI92EntryLevelSQL() throws java.sql.SQLException {
        return delegate.supportsANSI92EntryLevelSQL();
    }

    @Override
    public boolean supportsANSI92FullSQL() throws java.sql.SQLException {
        return delegate.supportsANSI92FullSQL();
    }

    @Override
    public boolean supportsANSI92IntermediateSQL() throws java.sql.SQLException {
        return delegate.supportsANSI92IntermediateSQL();
    }

    @Override
    public boolean supportsAlterTableWithAddColumn() throws java.sql.SQLException {
        return delegate.supportsAlterTableWithAddColumn();
    }

    @Override
    public boolean supportsAlterTableWithDropColumn() throws java.sql.SQLException {
        return delegate.supportsAlterTableWithDropColumn();
    }

    @Override
    public boolean supportsBatchUpdates() throws java.sql.SQLException {
        return delegate.supportsBatchUpdates();
    }

    @Override
    public boolean supportsCatalogsInDataManipulation() throws java.sql.SQLException {
        return delegate.supportsCatalogsInDataManipulation();
    }

    @Override
    public boolean supportsCatalogsInIndexDefinitions() throws java.sql.SQLException {
        return delegate.supportsCatalogsInIndexDefinitions();
    }

    @Override
    public boolean supportsCatalogsInPrivilegeDefinitions() throws java.sql.SQLException {
        return delegate.supportsCatalogsInPrivilegeDefinitions();
    }

    @Override
    public boolean supportsCatalogsInProcedureCalls() throws java.sql.SQLException {
        return delegate.supportsCatalogsInProcedureCalls();
    }

    @Override
    public boolean supportsCatalogsInTableDefinitions() throws java.sql.SQLException {
        return delegate.supportsCatalogsInTableDefinitions();
    }

    @Override
    public boolean supportsColumnAliasing() throws java.sql.SQLException {
        return delegate.supportsColumnAliasing();
    }

    @Override
    public boolean supportsConvert() throws java.sql.SQLException {
        return delegate.supportsConvert();
    }

    @Override
    public boolean supportsConvert(int p0, int p1) throws java.sql.SQLException {
        return delegate.supportsConvert(p0, p1);
    }

    @Override
    public boolean supportsCoreSQLGrammar() throws java.sql.SQLException {
        return delegate.supportsCoreSQLGrammar();
    }

    @Override
    public boolean supportsCorrelatedSubqueries() throws java.sql.SQLException {
        return delegate.supportsCorrelatedSubqueries();
    }

    @Override
    public boolean supportsDataDefinitionAndDataManipulationTransactions() throws java.sql.SQLException {
        return delegate.supportsDataDefinitionAndDataManipulationTransactions();
    }

    @Override
    public boolean supportsDataManipulationTransactionsOnly() throws java.sql.SQLException {
        return delegate.supportsDataManipulationTransactionsOnly();
    }

    @Override
    public boolean supportsDifferentTableCorrelationNames() throws java.sql.SQLException {
        return delegate.supportsDifferentTableCorrelationNames();
    }

    @Override
    public boolean supportsExpressionsInOrderBy() throws java.sql.SQLException {
        return delegate.supportsExpressionsInOrderBy();
    }

    @Override
    public boolean supportsExtendedSQLGrammar() throws java.sql.SQLException {
        return delegate.supportsExtendedSQLGrammar();
    }

    @Override
    public boolean supportsFullOuterJoins() throws java.sql.SQLException {
        return delegate.supportsFullOuterJoins();
    }

    @Override
    public boolean supportsGetGeneratedKeys() throws java.sql.SQLException {
        return delegate.supportsGetGeneratedKeys();
    }

    @Override
    public boolean supportsGroupBy() throws java.sql.SQLException {
        return delegate.supportsGroupBy();
    }

    @Override
    public boolean supportsGroupByBeyondSelect() throws java.sql.SQLException {
        return delegate.supportsGroupByBeyondSelect();
    }

    @Override
    public boolean supportsGroupByUnrelated() throws java.sql.SQLException {
        return delegate.supportsGroupByUnrelated();
    }

    @Override
    public boolean supportsIntegrityEnhancementFacility() throws java.sql.SQLException {
        return delegate.supportsIntegrityEnhancementFacility();
    }

    @Override
    public boolean supportsLikeEscapeClause() throws java.sql.SQLException {
        return delegate.supportsLikeEscapeClause();
    }

    @Override
    public boolean supportsLimitedOuterJoins() throws java.sql.SQLException {
        return delegate.supportsLimitedOuterJoins();
    }

    @Override
    public boolean supportsMinimumSQLGrammar() throws java.sql.SQLException {
        return delegate.supportsMinimumSQLGrammar();
    }

    @Override
    public boolean supportsMixedCaseIdentifiers() throws java.sql.SQLException {
        return delegate.supportsMixedCaseIdentifiers();
    }

    @Override
    public boolean supportsMixedCaseQuotedIdentifiers() throws java.sql.SQLException {
        return delegate.supportsMixedCaseQuotedIdentifiers();
    }

    @Override
    public boolean supportsMultipleOpenResults() throws java.sql.SQLException {
        return delegate.supportsMultipleOpenResults();
    }

    @Override
    public boolean supportsMultipleResultSets() throws java.sql.SQLException {
        return delegate.supportsMultipleResultSets();
    }

    @Override
    public boolean supportsMultipleTransactions() throws java.sql.SQLException {
        return delegate.supportsMultipleTransactions();
    }

    @Override
    public boolean supportsNamedParameters() throws java.sql.SQLException {
        return delegate.supportsNamedParameters();
    }

    @Override
    public boolean supportsNonNullableColumns() throws java.sql.SQLException {
        return delegate.supportsNonNullableColumns();
    }

    @Override
    public boolean supportsOpenCursorsAcrossCommit() throws java.sql.SQLException {
        return delegate.supportsOpenCursorsAcrossCommit();
    }

    @Override
    public boolean supportsOpenCursorsAcrossRollback() throws java.sql.SQLException {
        return delegate.supportsOpenCursorsAcrossRollback();
    }

    @Override
    public boolean supportsOpenStatementsAcrossCommit() throws java.sql.SQLException {
        return delegate.supportsOpenStatementsAcrossCommit();
    }

    @Override
    public boolean supportsOpenStatementsAcrossRollback() throws java.sql.SQLException {
        return delegate.supportsOpenStatementsAcrossRollback();
    }

    @Override
    public boolean supportsOrderByUnrelated() throws java.sql.SQLException {
        return delegate.supportsOrderByUnrelated();
    }

    @Override
    public boolean supportsOuterJoins() throws java.sql.SQLException {
        return delegate.supportsOuterJoins();
    }

    @Override
    public boolean supportsPositionedDelete() throws java.sql.SQLException {
        return delegate.supportsPositionedDelete();
    }

    @Override
    public boolean supportsPositionedUpdate() throws java.sql.SQLException {
        return delegate.supportsPositionedUpdate();
    }

    @Override
    public boolean supportsRefCursors() throws java.sql.SQLException {
        return delegate.supportsRefCursors();
    }

    @Override
    public boolean supportsResultSetConcurrency(int p0, int p1) throws java.sql.SQLException {
        return delegate.supportsResultSetConcurrency(p0, p1);
    }

    @Override
    public boolean supportsResultSetHoldability(int p0) throws java.sql.SQLException {
        return delegate.supportsResultSetHoldability(p0);
    }

    @Override
    public boolean supportsResultSetType(int p0) throws java.sql.SQLException {
        return delegate.supportsResultSetType(p0);
    }

    @Override
    public boolean supportsSavepoints() throws java.sql.SQLException {
        return delegate.supportsSavepoints();
    }

    @Override
    public boolean supportsSchemasInDataManipulation() throws java.sql.SQLException {
        return delegate.supportsSchemasInDataManipulation();
    }

    @Override
    public boolean supportsSchemasInIndexDefinitions() throws java.sql.SQLException {
        return delegate.supportsSchemasInIndexDefinitions();
    }

    @Override
    public boolean supportsSchemasInPrivilegeDefinitions() throws java.sql.SQLException {
        return delegate.supportsSchemasInPrivilegeDefinitions();
    }

    @Override
    public boolean supportsSchemasInProcedureCalls() throws java.sql.SQLException {
        return delegate.supportsSchemasInProcedureCalls();
    }

    @Override
    public boolean supportsSchemasInTableDefinitions() throws java.sql.SQLException {
        return delegate.supportsSchemasInTableDefinitions();
    }

    @Override
    public boolean supportsSelectForUpdate() throws java.sql.SQLException {
        return delegate.supportsSelectForUpdate();
    }

    @Override
    public boolean supportsSharding() throws java.sql.SQLException {
        return delegate.supportsSharding();
    }

    @Override
    public boolean supportsStatementPooling() throws java.sql.SQLException {
        return delegate.supportsStatementPooling();
    }

    @Override
    public boolean supportsStoredFunctionsUsingCallSyntax() throws java.sql.SQLException {
        return delegate.supportsStoredFunctionsUsingCallSyntax();
    }

    @Override
    public boolean supportsStoredProcedures() throws java.sql.SQLException {
        return delegate.supportsStoredProcedures();
    }

    @Override
    public boolean supportsSubqueriesInComparisons() throws java.sql.SQLException {
        return delegate.supportsSubqueriesInComparisons();
    }

    @Override
    public boolean supportsSubqueriesInExists() throws java.sql.SQLException {
        return delegate.supportsSubqueriesInExists();
    }

    @Override
    public boolean supportsSubqueriesInIns() throws java.sql.SQLException {
        return delegate.supportsSubqueriesInIns();
    }

    @Override
    public boolean supportsSubqueriesInQuantifieds() throws java.sql.SQLException {
        return delegate.supportsSubqueriesInQuantifieds();
    }

    @Override
    public boolean supportsTableCorrelationNames() throws java.sql.SQLException {
        return delegate.supportsTableCorrelationNames();
    }

    @Override
    public boolean supportsTransactionIsolationLevel(int p0) throws java.sql.SQLException {
        return delegate.supportsTransactionIsolationLevel(p0);
    }

    @Override
    public boolean supportsTransactions() throws java.sql.SQLException {
        return delegate.supportsTransactions();
    }

    @Override
    public boolean supportsUnion() throws java.sql.SQLException {
        return delegate.supportsUnion();
    }

    @Override
    public boolean supportsUnionAll() throws java.sql.SQLException {
        return delegate.supportsUnionAll();
    }

    @Override
    public boolean updatesAreDetected(int p0) throws java.sql.SQLException {
        return delegate.updatesAreDetected(p0);
    }

    @Override
    public boolean usesLocalFilePerTable() throws java.sql.SQLException {
        return delegate.usesLocalFilePerTable();
    }

    @Override
    public boolean usesLocalFiles() throws java.sql.SQLException {
        return delegate.usesLocalFiles();
    }
}
