/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import java.sql.ResultSet;

/**
 * Forwards every {@link ResultSet} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingResultSet implements ResultSet {

    protected final ResultSet delegate;

    protected ForwardingResultSet(ResultSet delegate) {
        this.delegate = delegate;
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public boolean absolute(int p0) throws java.sql.SQLException {
        return delegate.absolute(p0);
    }

    @Override
    public void afterLast() throws java.sql.SQLException {
        delegate.afterLast();
    }

    @Override
    public void beforeFirst() throws java.sql.SQLException {
        delegate.beforeFirst();
    }

    @Override
    public void cancelRowUpdates() throws java.sql.SQLException {
        delegate.cancelRowUpdates();
    }

    @Override
    public void clearWarnings() throws java.sql.SQLException {
        delegate.clearWarnings();
    }

    @Override
    public void close() throws java.sql.SQLException {
        delegate.close();
    }

    @Override
    public void deleteRow() throws java.sql.SQLException {
        delegate.deleteRow();
    }

    @Override
    public int findColumn(java.lang.String p0) throws java.sql.SQLException {
        return delegate.findColumn(p0);
    }

    @Override
    public boolean first() throws java.sql.SQLException {
        return delegate.first();
    }

    @Override
    public java.sql.Array getArray(int p0) throws java.sql.SQLException {
        return delegate.getArray(p0);
    }

    @Override
    public java.sql.Array getArray(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getArray(p0);
    }

    @Override
    public java.io.InputStream getAsciiStream(int p0) throws java.sql.SQLException {
        return delegate.getAsciiStream(p0);
    }

    @Override
    public java.io.InputStream getAsciiStream(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getAsciiStream(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(int p0) throws java.sql.SQLException {
        return delegate.getBigDecimal(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getBigDecimal(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(int p0, int p1) throws java.sql.SQLException {
        return delegate.getBigDecimal(p0, p1);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(java.lang.String p0, int p1) throws java.sql.SQLException {
        return delegate.getBigDecimal(p0, p1);
    }

    @Override
    public java.io.InputStream getBinaryStream(int p0) throws java.sql.SQLException {
        return delegate.getBinaryStream(p0);
    }

    @Override
    public java.io.InputStream getBinaryStream(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getBinaryStream(p0);
    }

    @Override
    public java.sql.Blob getBlob(int p0) throws java.sql.SQLException {
        return delegate.getBlob(p0);
    }

    @Override
    public java.sql.Blob getBlob(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getBlob(p0);
    }

    @Override
    public boolean getBoolean(int p0) throws java.sql.SQLException {
        return delegate.getBoolean(p0);
    }

    @Override
    public boolean getBoolean(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getBoolean(p0);
    }

    @Override
    public byte getByte(int p0) throws java.sql.SQLException {
        return delegate.getByte(p0);
    }

    @Override
    public byte getByte(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getByte(p0);
    }

    @Override
    public byte[] getBytes(int p0) throws java.sql.SQLException {
        return delegate.getBytes(p0);
    }

    @Override
    public byte[] getBytes(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getBytes(p0);
    }

    @Override
    public java.io.Reader getCharacterStream(int p0) throws java.sql.SQLException {
        return delegate.getCharacterStream(p0);
    }

    @Override
    public java.io.Reader getCharacterStream(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getCharacterStream(p0);
    }

    @Override
    public java.sql.Clob getClob(int p0) throws java.sql.SQLException {
        return delegate.getClob(p0);
    }

    @Override
    public java.sql.Clob getClob(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getClob(p0);
    }

    @Override
    public int getConcurrency() throws java.sql.SQLException {
        return delegate.getConcurrency();
    }

    @Override
    public java.lang.String getCursorName() throws java.sql.SQLException {
        return delegate.getCursorName();
    }

    @Override
    public java.sql.Date getDate(int p0) throws java.sql.SQLException {
        return delegate.getDate(p0);
    }

    @Override
    public java.sql.Date getDate(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getDate(p0);
    }

    @Override
    public java.sql.Date getDate(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getDate(p0, p1);
    }

    @Override
    public java.sql.Date getDate(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getDate(p0, p1);
    }

    @Override
    public double getDouble(int p0) throws java.sql.SQLException {
        return delegate.getDouble(p0);
    }

    @Override
    public double getDouble(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getDouble(p0);
    }

    @Override
    public int getFetchDirection() throws java.sql.SQLException {
        return delegate.getFetchDirection();
    }

    @Override
    public int getFetchSize() throws java.sql.SQLException {
        return delegate.getFetchSize();
    }

    @Override
    public float getFloat(int p0) throws java.sql.SQLException {
        return delegate.getFloat(p0);
    }

    @Override
    public float getFloat(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getFloat(p0);
    }

    @Override
    public int getHoldability() throws java.sql.SQLException {
        return delegate.getHoldability();
    }

    @Override
    public int getInt(int p0) throws java.sql.SQLException {
        return delegate.getInt(p0);
    }

    @Override
    public int getInt(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getInt(p0);
    }

    @Override
    public long getLong(int p0) throws java.sql.SQLException {
        return delegate.getLong(p0);
    }

    @Override
    public long getLong(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getLong(p0);
    }

    @Override
    public java.sql.ResultSetMetaData getMetaData() throws java.sql.SQLException {
        return delegate.getMetaData();
    }

    @Override
    public java.io.Reader getNCharacterStream(int p0) throws java.sql.SQLException {
        return delegate.getNCharacterStream(p0);
    }

    @Override
    public java.io.Reader getNCharacterStream(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getNCharacterStream(p0);
    }

    @Override
    public java.sql.NClob getNClob(int p0) throws java.sql.SQLException {
        return delegate.getNClob(p0);
    }

    @Override
    public java.sql.NClob getNClob(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getNClob(p0);
    }

    @Override
    public java.lang.String getNString(int p0) throws java.sql.SQLException {
        return delegate.getNString(p0);
    }

    @Override
    public java.lang.String getNString(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getNString(p0);
    }

    @Override
    public java.lang.Object getObject(int p0) throws java.sql.SQLException {
        return delegate.getObject(p0);
    }

    @Override
    public java.lang.Object getObject(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getObject(p0);
    }

    @Override
    public <T> T getObject(int p0, java.lang.Class<T> p1) throws java.sql.SQLException {
        return delegate.getObject(p0, p1);
    }

    @Override
    public java.lang.Object getObject(int p0, java.util.Map<java.lang.String, java.lang.Class<?>> p1) throws java.sql.SQLException {
        return delegate.getObject(p0, p1);
    }

    @Override
    public <T> T getObject(java.lang.String p0, java.lang.Class<T> p1) throws java.sql.SQLException {
        return delegate.getObject(p0, p1);
    }

    @Override
    public java.lang.Object getObject(java.lang.String p0, java.util.Map<java.lang.String, java.lang.Class<?>> p1) throws java.sql.SQLException {
        return delegate.getObject(p0, p1);
    }

    @Override
    public java.sql.Ref getRef(int p0) throws java.sql.SQLException {
        return delegate.getRef(p0);
    }

    @Override
    public java.sql.Ref getRef(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getRef(p0);
    }

    @Override
    public int getRow() throws java.sql.SQLException {
        return delegate.getRow();
    }

    @Override
    public java.sql.RowId getRowId(int p0) throws java.sql.SQLException {
        return delegate.getRowId(p0);
    }

    @Override
    public java.sql.RowId getRowId(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getRowId(p0);
    }

    @Override
    public java.sql.SQLXML getSQLXML(int p0) throws java.sql.SQLException {
        return delegate.getSQLXML(p0);
    }

    @Override
    public java.sql.SQLXML getSQLXML(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getSQLXML(p0);
    }

    @Override
    public short getShort(int p0) throws java.sql.SQLException {
        return delegate.getShort(p0);
    }

    @Override
    public short getShort(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getShort(p0);
    }

    @Override
    public java.sql.Statement getStatement() throws java.sql.SQLException {
        return delegate.getStatement();
    }

    @Override
    public java.lang.String getString(int p0) throws java.sql.SQLException {
        return delegate.getString(p0);
    }

    @Override
    public java.lang.String getString(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getString(p0);
    }

    @Override
    public java.sql.Time getTime(int p0) throws java.sql.SQLException {
        return delegate.getTime(p0);
    }

    @Override
    public java.sql.Time getTime(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getTime(p0);
    }

    @Override
    public java.sql.Time getTime(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getTime(p0, p1);
    }

    @Override
    public java.sql.Time getTime(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getTime(p0, p1);
    }

    @Override
    public java.sql.Timestamp getTimestamp(int p0) throws java.sql.SQLException {
        return delegate.getTimestamp(p0);
    }

    @Override
    public java.sql.Timestamp getTimestamp(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getTimestamp(p0);
    }

    @Override
    public java.sql.Timestamp getTimestamp(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getTimestamp(p0, p1);
    }

    @Override
    public java.sql.Timestamp getTimestamp(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return delegate.getTimestamp(p0, p1);
    }

    @Override
    public int getType() throws java.sql.SQLException {
        return delegate.getType();
    }

    @Override
    public java.net.URL getURL(int p0) throws java.sql.SQLException {
        return delegate.getURL(p0);
    }

    @Override
    public java.net.URL getURL(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getURL(p0);
    }

    @Override
    public java.io.InputStream getUnicodeStream(int p0) throws java.sql.SQLException {
        return delegate.getUnicodeStream(p0);
    }

    @Override
    public java.io.InputStream getUnicodeStream(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getUnicodeStream(p0);
    }

    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException {
        return delegate.getWarnings();
    }

    @Override
    public void insertRow() throws java.sql.SQLException {
        delegate.insertRow();
    }

    @Override
    public boolean isAfterLast() throws java.sql.SQLException {
        return delegate.isAfterLast();
    }

    @Override
    public boolean isBeforeFirst() throws java.sql.SQLException {
        return delegate.isBeforeFirst();
    }

    @Override
    public boolean isClosed() throws java.sql.SQLException {
        return delegate.isClosed();
    }

    @Override
    public boolean isFirst() throws java.sql.SQLException {
        return delegate.isFirst();
    }

    @Override
    public boolean isLast() throws java.sql.SQLException {
        return delegate.isLast();
    }

    @Override
    public boolean last() throws java.sql.SQLException {
        return delegate.last();
    }

    @Override
    public void moveToCurrentRow() throws java.sql.SQLException {
        delegate.moveToCurrentRow();
    }

    @Override
    public void moveToInsertRow() throws java.sql.SQLException {
        delegate.moveToInsertRow();
    }

    @Override
    public boolean next() throws java.sql.SQLException {
        return delegate.next();
    }

    @Override
    public boolean previous() throws java.sql.SQLException {
        return delegate.previous();
    }

    @Override
    public void refreshRow() throws java.sql.SQLException {
        delegate.refreshRow();
    }

    @Override
    public boolean relative(int p0) throws java.sql.SQLException {
        return delegate.relative(p0);
    }

    @Override
    public boolean rowDeleted() throws java.sql.SQLException {
        return delegate.rowDeleted();
    }

    @Override
    public boolean rowInserted() throws java.sql.SQLException {
        return delegate.rowInserted();
    }

    @Override
    public boolean rowUpdated() throws java.sql.SQLException {
        return delegate.rowUpdated();
    }

    @Override
    public void setFetchDirection(int p0) throws java.sql.SQLException {
        delegate.setFetchDirection(p0);
    }

    @Override
    public void setFetchSize(int p0) throws java.sql.SQLException {
        delegate.setFetchSize(p0);
    }

    @Override
    public void updateArray(int p0, java.sql.Array p1) throws java.sql.SQLException {
        delegate.updateArray(p0, p1);
    }

    @Override
    public void updateArray(java.lang.String p0, java.sql.Array p1) throws java.sql.SQLException {
        delegate.updateArray(p0, p1);
    }

    @Override
    public void updateAsciiStream(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1);
    }

    @Override
    public void updateAsciiStream(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1);
    }

    @Override
    public void updateAsciiStream(int p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1, p2);
    }

    @Override
    public void updateAsciiStream(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1, p2);
    }

    @Override
    public void updateAsciiStream(java.lang.String p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1, p2);
    }

    @Override
    public void updateAsciiStream(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateAsciiStream(p0, p1, p2);
    }

    @Override
    public void updateBigDecimal(int p0, java.math.BigDecimal p1) throws java.sql.SQLException {
        delegate.updateBigDecimal(p0, p1);
    }

    @Override
    public void updateBigDecimal(java.lang.String p0, java.math.BigDecimal p1) throws java.sql.SQLException {
        delegate.updateBigDecimal(p0, p1);
    }

    @Override
    public void updateBinaryStream(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1);
    }

    @Override
    public void updateBinaryStream(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1);
    }

    @Override
    public void updateBinaryStream(int p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1, p2);
    }

    @Override
    public void updateBinaryStream(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1, p2);
    }

    @Override
    public void updateBinaryStream(java.lang.String p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1, p2);
    }

    @Override
    public void updateBinaryStream(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateBinaryStream(p0, p1, p2);
    }

    @Override
    public void updateBlob(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1);
    }

    @Override
    public void updateBlob(int p0, java.sql.Blob p1) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1);
    }

    @Override
    public void updateBlob(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1);
    }

    @Override
    public void updateBlob(java.lang.String p0, java.sql.Blob p1) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1);
    }

    @Override
    public void updateBlob(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1, p2);
    }

    @Override
    public void updateBlob(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        delegate.updateBlob(p0, p1, p2);
    }

    @Override
    public void updateBoolean(int p0, boolean p1) throws java.sql.SQLException {
        delegate.updateBoolean(p0, p1);
    }

    @Override
    public void updateBoolean(java.lang.String p0, boolean p1) throws java.sql.SQLException {
        delegate.updateBoolean(p0, p1);
    }

    @Override
    public void updateByte(int p0, byte p1) throws java.sql.SQLException {
        delegate.updateByte(p0, p1);
    }

    @Override
    public void updateByte(java.lang.String p0, byte p1) throws java.sql.SQLException {
        delegate.updateByte(p0, p1);
    }

    @Override
    public void updateBytes(int p0, byte[] p1) throws java.sql.SQLException {
        delegate.updateBytes(p0, p1);
    }

    @Override
    public void updateBytes(java.lang.String p0, byte[] p1) throws java.sql.SQLException {
        delegate.updateBytes(p0, p1);
    }

    @Override
    public void updateCharacterStream(int p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1);
    }

    @Override
    public void updateCharacterStream(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1);
    }

    @Override
    public void updateCharacterStream(int p0, java.io.Reader p1, int p2) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateCharacterStream(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateCharacterStream(java.lang.String p0, java.io.Reader p1, int p2) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateCharacterStream(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateClob(int p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateClob(p0, p1);
    }

    @Override
    public void updateClob(int p0, java.sql.Clob p1) throws java.sql.SQLException {
        delegate.updateClob(p0, p1);
    }

    @Override
    public void updateClob(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateClob(p0, p1);
    }

    @Override
    public void updateClob(java.lang.String p0, java.sql.Clob p1) throws java.sql.SQLException {
        delegate.updateClob(p0, p1);
    }

    @Override
    public void updateClob(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateClob(p0, p1, p2);
    }

    @Override
    public void updateClob(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateClob(p0, p1, p2);
    }

    @Override
    public void updateDate(int p0, java.sql.Date p1) throws java.sql.SQLException {
        delegate.updateDate(p0, p1);
    }

    @Override
    public void updateDate(java.lang.String p0, java.sql.Date p1) throws java.sql.SQLException {
        delegate.updateDate(p0, p1);
    }

    @Override
    public void updateDouble(int p0, double p1) throws java.sql.SQLException {
        delegate.updateDouble(p0, p1);
    }

    @Override
    public void updateDouble(java.lang.String p0, double p1) throws java.sql.SQLException {
        delegate.updateDouble(p0, p1);
    }

    @Override
    public void updateFloat(int p0, float p1) throws java.sql.SQLException {
        delegate.updateFloat(p0, p1);
    }

    @Override
    public void updateFloat(java.lang.String p0, float p1) throws java.sql.SQLException {
        delegate.updateFloat(p0, p1);
    }

    @Override
    public void updateInt(int p0, int p1) throws java.sql.SQLException {
        delegate.updateInt(p0, p1);
    }

    @Override
    public void updateInt(java.lang.String p0, int p1) throws java.sql.SQLException {
        delegate.updateInt(p0, p1);
    }

    @Override
    public void updateLong(int p0, long p1) throws java.sql.SQLException {
        delegate.updateLong(p0, p1);
    }

    @Override
    public void updateLong(java.lang.String p0, long p1) throws java.sql.SQLException {
        delegate.updateLong(p0, p1);
    }

    @Override
    public void updateNCharacterStream(int p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateNCharacterStream(p0, p1);
    }

    @Override
    public void updateNCharacterStream(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateNCharacterStream(p0, p1);
    }

    @Override
    public void updateNCharacterStream(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateNCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateNCharacterStream(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateNCharacterStream(p0, p1, p2);
    }

    @Override
    public void updateNClob(int p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1);
    }

    @Override
    public void updateNClob(int p0, java.sql.NClob p1) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1);
    }

    @Override
    public void updateNClob(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1);
    }

    @Override
    public void updateNClob(java.lang.String p0, java.sql.NClob p1) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1);
    }

    @Override
    public void updateNClob(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1, p2);
    }

    @Override
    public void updateNClob(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        delegate.updateNClob(p0, p1, p2);
    }

    @Override
    public void updateNString(int p0, java.lang.String p1) throws java.sql.SQLException {
        delegate.updateNString(p0, p1);
    }

    @Override
    public void updateNString(java.lang.String p0, java.lang.String p1) throws java.sql.SQLException {
        delegate.updateNString(p0, p1);
    }

    @Override
    public void updateNull(int p0) throws java.sql.SQLException {
        delegate.updateNull(p0);
    }

    @Override
    public void updateNull(java.lang.String p0) throws java.sql.SQLException {
        delegate.updateNull(p0);
    }

    @Override
    public void updateObject(int p0, java.lang.Object p1) throws java.sql.SQLException {
        delegate.updateObject(p0, p1);
    }

    @Override
    public void updateObject(java.lang.String p0, java.lang.Object p1) throws java.sql.SQLException {
        delegate.updateObject(p0, p1);
    }

    @Override
    public void updateObject(int p0, java.lang.Object p1, int p2) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2);
    }

    @Override
    public void updateObject(java.lang.String p0, java.lang.Object p1, int p2) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2);
    }

    @Override
    public void updateObject(int p0, java.lang.Object p1, java.sql.SQLType p2) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2);
    }

    @Override
    public void updateObject(java.lang.String p0, java.lang.Object p1, java.sql.SQLType p2) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2);
    }

    @Override
    public void updateObject(int p0, java.lang.Object p1, java.sql.SQLType p2, int p3) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2, p3);
    }

    @Override
    public void updateObject(java.lang.String p0, java.lang.Object p1, java.sql.SQLType p2, int p3) throws java.sql.SQLException {
        delegate.updateObject(p0, p1, p2, p3);
    }

    @Override
    public void updateRef(int p0, java.sql.Ref p1) throws java.sql.SQLException {
        delegate.updateRef(p0, p1);
    }

    @Override
    public void updateRef(java.lang.String p0, java.sql.Ref p1) throws java.sql.SQLException {
        delegate.updateRef(p0, p1);
    }

    @Override
    public void updateRow() throws java.sql.SQLException {
        delegate.updateRow();
    }

    @Override
    public void updateRowId(int p0, java.sql.RowId p1) throws java.sql.SQLException {
        delegate.updateRowId(p0, p1);
    }

    @Override
    public void updateRowId(java.lang.String p0, java.sql.RowId p1) throws java.sql.SQLException {
        delegate.updateRowId(p0, p1);
    }

    @Override
    public void updateSQLXML(int p0, java.sql.SQLXML p1) throws java.sql.SQLException {
        delegate.updateSQLXML(p0, p1);
    }

    @Override
    public void updateSQLXML(java.lang.String p0, java.sql.SQLXML p1) throws java.sql.SQLException {
        delegate.updateSQLXML(p0, p1);
    }

    @Override
    public void updateShort(int p0, short p1) throws java.sql.SQLException {
        delegate.updateShort(p0, p1);
    }

    @Override
    public void updateShort(java.lang.String p0, short p1) throws java.sql.SQLException {
        delegate.updateShort(p0, p1);
    }

    @Override
    public void updateString(int p0, java.lang.String p1) throws java.sql.SQLException {
        delegate.updateString(p0, p1);
    }

    @Override
    public void updateString(java.lang.String p0, java.lang.String p1) throws java.sql.SQLException {
        delegate.updateString(p0, p1);
    }

    @Override
    public void updateTime(int p0, java.sql.Time p1) throws java.sql.SQLException {
        delegate.updateTime(p0, p1);
    }

    @Override
    public void updateTime(java.lang.String p0, java.sql.Time p1) throws java.sql.SQLException {
        delegate.updateTime(p0, p1);
    }

    @Override
    public void updateTimestamp(int p0, java.sql.Timestamp p1) throws java.sql.SQLException {
        delegate.updateTimestamp(p0, p1);
    }

    @Override
    public void updateTimestamp(java.lang.String p0, java.sql.Timestamp p1) throws java.sql.SQLException {
        delegate.updateTimestamp(p0, p1);
    }

    @Override
    public boolean wasNull() throws java.sql.SQLException {
        return delegate.wasNull();
    }
}
