/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 */

package io.crate.client.jdbc;

import java.sql.CallableStatement;
import java.sql.SQLException;

/**
 * Forwards every {@link CallableStatement} method CratePreparedStatement does not answer.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingCallableStatement extends CratePreparedStatement implements CallableStatement {

    protected final CallableStatement callableDelegate;

    protected ForwardingCallableStatement(CallableStatement delegate, CrateConnection connection) throws SQLException {
        super(delegate, connection);
        this.callableDelegate = delegate;
    }

    @Override
    public java.sql.Array getArray(int p0) throws java.sql.SQLException {
        return callableDelegate.getArray(p0);
    }

    @Override
    public java.sql.Array getArray(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getArray(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(int p0) throws java.sql.SQLException {
        return callableDelegate.getBigDecimal(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getBigDecimal(p0);
    }

    @Override
    public java.math.BigDecimal getBigDecimal(int p0, int p1) throws java.sql.SQLException {
        return callableDelegate.getBigDecimal(p0, p1);
    }

    @Override
    public java.sql.Blob getBlob(int p0) throws java.sql.SQLException {
        return callableDelegate.getBlob(p0);
    }

    @Override
    public java.sql.Blob getBlob(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getBlob(p0);
    }

    @Override
    public boolean getBoolean(int p0) throws java.sql.SQLException {
        return callableDelegate.getBoolean(p0);
    }

    @Override
    public boolean getBoolean(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getBoolean(p0);
    }

    @Override
    public byte getByte(int p0) throws java.sql.SQLException {
        return callableDelegate.getByte(p0);
    }

    @Override
    public byte getByte(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getByte(p0);
    }

    @Override
    public byte[] getBytes(int p0) throws java.sql.SQLException {
        return callableDelegate.getBytes(p0);
    }

    @Override
    public byte[] getBytes(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getBytes(p0);
    }

    @Override
    public java.io.Reader getCharacterStream(int p0) throws java.sql.SQLException {
        return callableDelegate.getCharacterStream(p0);
    }

    @Override
    public java.io.Reader getCharacterStream(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getCharacterStream(p0);
    }

    @Override
    public java.sql.Clob getClob(int p0) throws java.sql.SQLException {
        return callableDelegate.getClob(p0);
    }

    @Override
    public java.sql.Clob getClob(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getClob(p0);
    }

    @Override
    public java.sql.Date getDate(int p0) throws java.sql.SQLException {
        return callableDelegate.getDate(p0);
    }

    @Override
    public java.sql.Date getDate(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getDate(p0);
    }

    @Override
    public java.sql.Date getDate(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getDate(p0, p1);
    }

    @Override
    public java.sql.Date getDate(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getDate(p0, p1);
    }

    @Override
    public double getDouble(int p0) throws java.sql.SQLException {
        return callableDelegate.getDouble(p0);
    }

    @Override
    public double getDouble(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getDouble(p0);
    }

    @Override
    public float getFloat(int p0) throws java.sql.SQLException {
        return callableDelegate.getFloat(p0);
    }

    @Override
    public float getFloat(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getFloat(p0);
    }

    @Override
    public int getInt(int p0) throws java.sql.SQLException {
        return callableDelegate.getInt(p0);
    }

    @Override
    public int getInt(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getInt(p0);
    }

    @Override
    public long getLong(int p0) throws java.sql.SQLException {
        return callableDelegate.getLong(p0);
    }

    @Override
    public long getLong(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getLong(p0);
    }

    @Override
    public java.io.Reader getNCharacterStream(int p0) throws java.sql.SQLException {
        return callableDelegate.getNCharacterStream(p0);
    }

    @Override
    public java.io.Reader getNCharacterStream(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getNCharacterStream(p0);
    }

    @Override
    public java.sql.NClob getNClob(int p0) throws java.sql.SQLException {
        return callableDelegate.getNClob(p0);
    }

    @Override
    public java.sql.NClob getNClob(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getNClob(p0);
    }

    @Override
    public java.lang.String getNString(int p0) throws java.sql.SQLException {
        return callableDelegate.getNString(p0);
    }

    @Override
    public java.lang.String getNString(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getNString(p0);
    }

    @Override
    public java.lang.Object getObject(int p0) throws java.sql.SQLException {
        return callableDelegate.getObject(p0);
    }

    @Override
    public java.lang.Object getObject(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getObject(p0);
    }

    @Override
    public <T> T getObject(int p0, java.lang.Class<T> p1) throws java.sql.SQLException {
        return callableDelegate.getObject(p0, p1);
    }

    @Override
    public java.lang.Object getObject(int p0, java.util.Map<java.lang.String, java.lang.Class<?>> p1) throws java.sql.SQLException {
        return callableDelegate.getObject(p0, p1);
    }

    @Override
    public <T> T getObject(java.lang.String p0, java.lang.Class<T> p1) throws java.sql.SQLException {
        return callableDelegate.getObject(p0, p1);
    }

    @Override
    public java.lang.Object getObject(java.lang.String p0, java.util.Map<java.lang.String, java.lang.Class<?>> p1) throws java.sql.SQLException {
        return callableDelegate.getObject(p0, p1);
    }

    @Override
    public java.sql.Ref getRef(int p0) throws java.sql.SQLException {
        return callableDelegate.getRef(p0);
    }

    @Override
    public java.sql.Ref getRef(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getRef(p0);
    }

    @Override
    public java.sql.RowId getRowId(int p0) throws java.sql.SQLException {
        return callableDelegate.getRowId(p0);
    }

    @Override
    public java.sql.RowId getRowId(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getRowId(p0);
    }

    @Override
    public java.sql.SQLXML getSQLXML(int p0) throws java.sql.SQLException {
        return callableDelegate.getSQLXML(p0);
    }

    @Override
    public java.sql.SQLXML getSQLXML(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getSQLXML(p0);
    }

    @Override
    public short getShort(int p0) throws java.sql.SQLException {
        return callableDelegate.getShort(p0);
    }

    @Override
    public short getShort(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getShort(p0);
    }

    @Override
    public java.lang.String getString(int p0) throws java.sql.SQLException {
        return callableDelegate.getString(p0);
    }

    @Override
    public java.lang.String getString(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getString(p0);
    }

    @Override
    public java.sql.Time getTime(int p0) throws java.sql.SQLException {
        return callableDelegate.getTime(p0);
    }

    @Override
    public java.sql.Time getTime(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getTime(p0);
    }

    @Override
    public java.sql.Time getTime(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getTime(p0, p1);
    }

    @Override
    public java.sql.Time getTime(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getTime(p0, p1);
    }

    @Override
    public java.sql.Timestamp getTimestamp(int p0) throws java.sql.SQLException {
        return callableDelegate.getTimestamp(p0);
    }

    @Override
    public java.sql.Timestamp getTimestamp(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getTimestamp(p0);
    }

    @Override
    public java.sql.Timestamp getTimestamp(int p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getTimestamp(p0, p1);
    }

    @Override
    public java.sql.Timestamp getTimestamp(java.lang.String p0, java.util.Calendar p1) throws java.sql.SQLException {
        return callableDelegate.getTimestamp(p0, p1);
    }

    @Override
    public java.net.URL getURL(int p0) throws java.sql.SQLException {
        return callableDelegate.getURL(p0);
    }

    @Override
    public java.net.URL getURL(java.lang.String p0) throws java.sql.SQLException {
        return callableDelegate.getURL(p0);
    }

    @Override
    public void registerOutParameter(int p0, int p1) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, int p1) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1);
    }

    @Override
    public void registerOutParameter(int p0, java.sql.SQLType p1) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, java.sql.SQLType p1) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1);
    }

    @Override
    public void registerOutParameter(int p0, int p1, int p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(int p0, int p1, java.lang.String p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, int p1, int p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, int p1, java.lang.String p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(int p0, java.sql.SQLType p1, int p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(int p0, java.sql.SQLType p1, java.lang.String p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, java.sql.SQLType p1, int p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void registerOutParameter(java.lang.String p0, java.sql.SQLType p1, java.lang.String p2) throws java.sql.SQLException {
        callableDelegate.registerOutParameter(p0, p1, p2);
    }

    @Override
    public void setAsciiStream(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        callableDelegate.setAsciiStream(p0, p1);
    }

    @Override
    public void setAsciiStream(java.lang.String p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        callableDelegate.setAsciiStream(p0, p1, p2);
    }

    @Override
    public void setAsciiStream(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        callableDelegate.setAsciiStream(p0, p1, p2);
    }

    @Override
    public void setBigDecimal(java.lang.String p0, java.math.BigDecimal p1) throws java.sql.SQLException {
        callableDelegate.setBigDecimal(p0, p1);
    }

    @Override
    public void setBinaryStream(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        callableDelegate.setBinaryStream(p0, p1);
    }

    @Override
    public void setBinaryStream(java.lang.String p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        callableDelegate.setBinaryStream(p0, p1, p2);
    }

    @Override
    public void setBinaryStream(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        callableDelegate.setBinaryStream(p0, p1, p2);
    }

    @Override
    public void setBlob(java.lang.String p0, java.io.InputStream p1) throws java.sql.SQLException {
        callableDelegate.setBlob(p0, p1);
    }

    @Override
    public void setBlob(java.lang.String p0, java.sql.Blob p1) throws java.sql.SQLException {
        callableDelegate.setBlob(p0, p1);
    }

    @Override
    public void setBlob(java.lang.String p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        callableDelegate.setBlob(p0, p1, p2);
    }

    @Override
    public void setBoolean(java.lang.String p0, boolean p1) throws java.sql.SQLException {
        callableDelegate.setBoolean(p0, p1);
    }

    @Override
    public void setByte(java.lang.String p0, byte p1) throws java.sql.SQLException {
        callableDelegate.setByte(p0, p1);
    }

    @Override
    public void setBytes(java.lang.String p0, byte[] p1) throws java.sql.SQLException {
        callableDelegate.setBytes(p0, p1);
    }

    @Override
    public void setCharacterStream(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        callableDelegate.setCharacterStream(p0, p1);
    }

    @Override
    public void setCharacterStream(java.lang.String p0, java.io.Reader p1, int p2) throws java.sql.SQLException {
        callableDelegate.setCharacterStream(p0, p1, p2);
    }

    @Override
    public void setCharacterStream(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        callableDelegate.setCharacterStream(p0, p1, p2);
    }

    @Override
    public void setClob(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        callableDelegate.setClob(p0, p1);
    }

    @Override
    public void setClob(java.lang.String p0, java.sql.Clob p1) throws java.sql.SQLException {
        callableDelegate.setClob(p0, p1);
    }

    @Override
    public void setClob(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        callableDelegate.setClob(p0, p1, p2);
    }

    @Override
    public void setDate(java.lang.String p0, java.sql.Date p1) throws java.sql.SQLException {
        callableDelegate.setDate(p0, p1);
    }

    @Override
    public void setDate(java.lang.String p0, java.sql.Date p1, java.util.Calendar p2) throws java.sql.SQLException {
        callableDelegate.setDate(p0, p1, p2);
    }

    @Override
    public void setDouble(java.lang.String p0, double p1) throws java.sql.SQLException {
        callableDelegate.setDouble(p0, p1);
    }

    @Override
    public void setFloat(java.lang.String p0, float p1) throws java.sql.SQLException {
        callableDelegate.setFloat(p0, p1);
    }

    @Override
    public void setInt(java.lang.String p0, int p1) throws java.sql.SQLException {
        callableDelegate.setInt(p0, p1);
    }

    @Override
    public void setLong(java.lang.String p0, long p1) throws java.sql.SQLException {
        callableDelegate.setLong(p0, p1);
    }

    @Override
    public void setNCharacterStream(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        callableDelegate.setNCharacterStream(p0, p1);
    }

    @Override
    public void setNCharacterStream(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        callableDelegate.setNCharacterStream(p0, p1, p2);
    }

    @Override
    public void setNClob(java.lang.String p0, java.io.Reader p1) throws java.sql.SQLException {
        callableDelegate.setNClob(p0, p1);
    }

    @Override
    public void setNClob(java.lang.String p0, java.sql.NClob p1) throws java.sql.SQLException {
        callableDelegate.setNClob(p0, p1);
    }

    @Override
    public void setNClob(java.lang.String p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        callableDelegate.setNClob(p0, p1, p2);
    }

    @Override
    public void setNString(java.lang.String p0, java.lang.String p1) throws java.sql.SQLException {
        callableDelegate.setNString(p0, p1);
    }

    @Override
    public void setNull(java.lang.String p0, int p1) throws java.sql.SQLException {
        callableDelegate.setNull(p0, p1);
    }

    @Override
    public void setNull(java.lang.String p0, int p1, java.lang.String p2) throws java.sql.SQLException {
        callableDelegate.setNull(p0, p1, p2);
    }

    @Override
    public void setObject(java.lang.String p0, java.lang.Object p1) throws java.sql.SQLException {
        callableDelegate.setObject(p0, p1);
    }

    @Override
    public void setObject(java.lang.String p0, java.lang.Object p1, int p2) throws java.sql.SQLException {
        callableDelegate.setObject(p0, p1, p2);
    }

    @Override
    public void setObject(java.lang.String p0, java.lang.Object p1, java.sql.SQLType p2) throws java.sql.SQLException {
        callableDelegate.setObject(p0, p1, p2);
    }

    @Override
    public void setObject(java.lang.String p0, java.lang.Object p1, int p2, int p3) throws java.sql.SQLException {
        callableDelegate.setObject(p0, p1, p2, p3);
    }

    @Override
    public void setObject(java.lang.String p0, java.lang.Object p1, java.sql.SQLType p2, int p3) throws java.sql.SQLException {
        callableDelegate.setObject(p0, p1, p2, p3);
    }

    @Override
    public void setRowId(java.lang.String p0, java.sql.RowId p1) throws java.sql.SQLException {
        callableDelegate.setRowId(p0, p1);
    }

    @Override
    public void setSQLXML(java.lang.String p0, java.sql.SQLXML p1) throws java.sql.SQLException {
        callableDelegate.setSQLXML(p0, p1);
    }

    @Override
    public void setShort(java.lang.String p0, short p1) throws java.sql.SQLException {
        callableDelegate.setShort(p0, p1);
    }

    @Override
    public void setString(java.lang.String p0, java.lang.String p1) throws java.sql.SQLException {
        callableDelegate.setString(p0, p1);
    }

    @Override
    public void setTime(java.lang.String p0, java.sql.Time p1) throws java.sql.SQLException {
        callableDelegate.setTime(p0, p1);
    }

    @Override
    public void setTime(java.lang.String p0, java.sql.Time p1, java.util.Calendar p2) throws java.sql.SQLException {
        callableDelegate.setTime(p0, p1, p2);
    }

    @Override
    public void setTimestamp(java.lang.String p0, java.sql.Timestamp p1) throws java.sql.SQLException {
        callableDelegate.setTimestamp(p0, p1);
    }

    @Override
    public void setTimestamp(java.lang.String p0, java.sql.Timestamp p1, java.util.Calendar p2) throws java.sql.SQLException {
        callableDelegate.setTimestamp(p0, p1, p2);
    }

    @Override
    public void setURL(java.lang.String p0, java.net.URL p1) throws java.sql.SQLException {
        callableDelegate.setURL(p0, p1);
    }

    @Override
    public boolean wasNull() throws java.sql.SQLException {
        return callableDelegate.wasNull();
    }
}
