/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Forwards every {@link PreparedStatement} method CrateStatement does not answer.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingPreparedStatement extends CrateStatement implements PreparedStatement {

    protected final PreparedStatement preparedDelegate;

    protected ForwardingPreparedStatement(PreparedStatement delegate, CrateConnection connection) throws SQLException {
        super(delegate, connection);
        this.preparedDelegate = delegate;
    }

    @Override
    public void addBatch() throws java.sql.SQLException {
        preparedDelegate.addBatch();
    }

    @Override
    public void clearParameters() throws java.sql.SQLException {
        preparedDelegate.clearParameters();
    }

    @Override
    public boolean execute() throws java.sql.SQLException {
        return preparedDelegate.execute();
    }

    @Override
    public long executeLargeUpdate() throws java.sql.SQLException {
        return preparedDelegate.executeLargeUpdate();
    }

    @Override
    public java.sql.ResultSet executeQuery() throws java.sql.SQLException {
        return preparedDelegate.executeQuery();
    }

    @Override
    public int executeUpdate() throws java.sql.SQLException {
        return preparedDelegate.executeUpdate();
    }

    @Override
    public java.sql.ResultSetMetaData getMetaData() throws java.sql.SQLException {
        return preparedDelegate.getMetaData();
    }

    @Override
    public java.sql.ParameterMetaData getParameterMetaData() throws java.sql.SQLException {
        return preparedDelegate.getParameterMetaData();
    }

    @Override
    public void setArray(int p0, java.sql.Array p1) throws java.sql.SQLException {
        preparedDelegate.setArray(p0, p1);
    }

    @Override
    public void setAsciiStream(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        preparedDelegate.setAsciiStream(p0, p1);
    }

    @Override
    public void setAsciiStream(int p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        preparedDelegate.setAsciiStream(p0, p1, p2);
    }

    @Override
    public void setAsciiStream(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setAsciiStream(p0, p1, p2);
    }

    @Override
    public void setBigDecimal(int p0, java.math.BigDecimal p1) throws java.sql.SQLException {
        preparedDelegate.setBigDecimal(p0, p1);
    }

    @Override
    public void setBinaryStream(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        preparedDelegate.setBinaryStream(p0, p1);
    }

    @Override
    public void setBinaryStream(int p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        preparedDelegate.setBinaryStream(p0, p1, p2);
    }

    @Override
    public void setBinaryStream(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setBinaryStream(p0, p1, p2);
    }

    @Override
    public void setBlob(int p0, java.io.InputStream p1) throws java.sql.SQLException {
        preparedDelegate.setBlob(p0, p1);
    }

    @Override
    public void setBlob(int p0, java.sql.Blob p1) throws java.sql.SQLException {
        preparedDelegate.setBlob(p0, p1);
    }

    @Override
    public void setBlob(int p0, java.io.InputStream p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setBlob(p0, p1, p2);
    }

    @Override
    public void setBoolean(int p0, boolean p1) throws java.sql.SQLException {
        preparedDelegate.setBoolean(p0, p1);
    }

    @Override
    public void setByte(int p0, byte p1) throws java.sql.SQLException {
        preparedDelegate.setByte(p0, p1);
    }

    @Override
    public void setBytes(int p0, byte[] p1) throws java.sql.SQLException {
        preparedDelegate.setBytes(p0, p1);
    }

    @Override
    public void setCharacterStream(int p0, java.io.Reader p1) throws java.sql.SQLException {
        preparedDelegate.setCharacterStream(p0, p1);
    }

    @Override
    public void setCharacterStream(int p0, java.io.Reader p1, int p2) throws java.sql.SQLException {
        preparedDelegate.setCharacterStream(p0, p1, p2);
    }

    @Override
    public void setCharacterStream(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setCharacterStream(p0, p1, p2);
    }

    @Override
    public void setClob(int p0, java.io.Reader p1) throws java.sql.SQLException {
        preparedDelegate.setClob(p0, p1);
    }

    @Override
    public void setClob(int p0, java.sql.Clob p1) throws java.sql.SQLException {
        preparedDelegate.setClob(p0, p1);
    }

    @Override
    public void setClob(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setClob(p0, p1, p2);
    }

    @Override
    public void setDate(int p0, java.sql.Date p1) throws java.sql.SQLException {
        preparedDelegate.setDate(p0, p1);
    }

    @Override
    public void setDate(int p0, java.sql.Date p1, java.util.Calendar p2) throws java.sql.SQLException {
        preparedDelegate.setDate(p0, p1, p2);
    }

    @Override
    public void setDouble(int p0, double p1) throws java.sql.SQLException {
        preparedDelegate.setDouble(p0, p1);
    }

    @Override
    public void setFloat(int p0, float p1) throws java.sql.SQLException {
        preparedDelegate.setFloat(p0, p1);
    }

    @Override
    public void setInt(int p0, int p1) throws java.sql.SQLException {
        preparedDelegate.setInt(p0, p1);
    }

    @Override
    public void setLong(int p0, long p1) throws java.sql.SQLException {
        preparedDelegate.setLong(p0, p1);
    }

    @Override
    public void setNCharacterStream(int p0, java.io.Reader p1) throws java.sql.SQLException {
        preparedDelegate.setNCharacterStream(p0, p1);
    }

    @Override
    public void setNCharacterStream(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setNCharacterStream(p0, p1, p2);
    }

    @Override
    public void setNClob(int p0, java.io.Reader p1) throws java.sql.SQLException {
        preparedDelegate.setNClob(p0, p1);
    }

    @Override
    public void setNClob(int p0, java.sql.NClob p1) throws java.sql.SQLException {
        preparedDelegate.setNClob(p0, p1);
    }

    @Override
    public void setNClob(int p0, java.io.Reader p1, long p2) throws java.sql.SQLException {
        preparedDelegate.setNClob(p0, p1, p2);
    }

    @Override
    public void setNString(int p0, java.lang.String p1) throws java.sql.SQLException {
        preparedDelegate.setNString(p0, p1);
    }

    @Override
    public void setNull(int p0, int p1) throws java.sql.SQLException {
        preparedDelegate.setNull(p0, p1);
    }

    @Override
    public void setNull(int p0, int p1, java.lang.String p2) throws java.sql.SQLException {
        preparedDelegate.setNull(p0, p1, p2);
    }

    @Override
    public void setObject(int p0, java.lang.Object p1) throws java.sql.SQLException {
        preparedDelegate.setObject(p0, p1);
    }

    @Override
    public void setObject(int p0, java.lang.Object p1, int p2) throws java.sql.SQLException {
        preparedDelegate.setObject(p0, p1, p2);
    }

    @Override
    public void setObject(int p0, java.lang.Object p1, java.sql.SQLType p2) throws java.sql.SQLException {
        preparedDelegate.setObject(p0, p1, p2);
    }

    @Override
    public void setObject(int p0, java.lang.Object p1, int p2, int p3) throws java.sql.SQLException {
        preparedDelegate.setObject(p0, p1, p2, p3);
    }

    @Override
    public void setObject(int p0, java.lang.Object p1, java.sql.SQLType p2, int p3) throws java.sql.SQLException {
        preparedDelegate.setObject(p0, p1, p2, p3);
    }

    @Override
    public void setRef(int p0, java.sql.Ref p1) throws java.sql.SQLException {
        preparedDelegate.setRef(p0, p1);
    }

    @Override
    public void setRowId(int p0, java.sql.RowId p1) throws java.sql.SQLException {
        preparedDelegate.setRowId(p0, p1);
    }

    @Override
    public void setSQLXML(int p0, java.sql.SQLXML p1) throws java.sql.SQLException {
        preparedDelegate.setSQLXML(p0, p1);
    }

    @Override
    public void setShort(int p0, short p1) throws java.sql.SQLException {
        preparedDelegate.setShort(p0, p1);
    }

    @Override
    public void setString(int p0, java.lang.String p1) throws java.sql.SQLException {
        preparedDelegate.setString(p0, p1);
    }

    @Override
    public void setTime(int p0, java.sql.Time p1) throws java.sql.SQLException {
        preparedDelegate.setTime(p0, p1);
    }

    @Override
    public void setTime(int p0, java.sql.Time p1, java.util.Calendar p2) throws java.sql.SQLException {
        preparedDelegate.setTime(p0, p1, p2);
    }

    @Override
    public void setTimestamp(int p0, java.sql.Timestamp p1) throws java.sql.SQLException {
        preparedDelegate.setTimestamp(p0, p1);
    }

    @Override
    public void setTimestamp(int p0, java.sql.Timestamp p1, java.util.Calendar p2) throws java.sql.SQLException {
        preparedDelegate.setTimestamp(p0, p1, p2);
    }

    @Override
    public void setURL(int p0, java.net.URL p1) throws java.sql.SQLException {
        preparedDelegate.setURL(p0, p1);
    }

    @Override
    public void setUnicodeStream(int p0, java.io.InputStream p1, int p2) throws java.sql.SQLException {
        preparedDelegate.setUnicodeStream(p0, p1, p2);
    }
}
