/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import java.sql.ResultSetMetaData;
import org.postgresql.PGResultSetMetaData;
import java.sql.SQLException;

/**
 * Forwards every {@link ResultSetMetaData} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingResultSetMetaData implements ResultSetMetaData, PGResultSetMetaData {

    protected final ResultSetMetaData delegate;
    protected final PGResultSetMetaData pgDelegate;

    protected ForwardingResultSetMetaData(ResultSetMetaData delegate) throws SQLException {
        this.delegate = delegate;
        this.pgDelegate = delegate.unwrap(PGResultSetMetaData.class);
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public java.lang.String getBaseColumnName(int p0) throws java.sql.SQLException {
        return pgDelegate.getBaseColumnName(p0);
    }

    @Override
    public java.lang.String getBaseSchemaName(int p0) throws java.sql.SQLException {
        return pgDelegate.getBaseSchemaName(p0);
    }

    @Override
    public java.lang.String getBaseTableName(int p0) throws java.sql.SQLException {
        return pgDelegate.getBaseTableName(p0);
    }

    @Override
    public java.lang.String getCatalogName(int p0) throws java.sql.SQLException {
        return delegate.getCatalogName(p0);
    }

    @Override
    public java.lang.String getColumnClassName(int p0) throws java.sql.SQLException {
        return delegate.getColumnClassName(p0);
    }

    @Override
    public int getColumnCount() throws java.sql.SQLException {
        return delegate.getColumnCount();
    }

    @Override
    public int getColumnDisplaySize(int p0) throws java.sql.SQLException {
        return delegate.getColumnDisplaySize(p0);
    }

    @Override
    public java.lang.String getColumnLabel(int p0) throws java.sql.SQLException {
        return delegate.getColumnLabel(p0);
    }

    @Override
    public java.lang.String getColumnName(int p0) throws java.sql.SQLException {
        return delegate.getColumnName(p0);
    }

    @Override
    public int getColumnType(int p0) throws java.sql.SQLException {
        return delegate.getColumnType(p0);
    }

    @Override
    public java.lang.String getColumnTypeName(int p0) throws java.sql.SQLException {
        return delegate.getColumnTypeName(p0);
    }

    @Override
    public int getFormat(int p0) throws java.sql.SQLException {
        return pgDelegate.getFormat(p0);
    }

    @Override
    public int getPrecision(int p0) throws java.sql.SQLException {
        return delegate.getPrecision(p0);
    }

    @Override
    public int getScale(int p0) throws java.sql.SQLException {
        return delegate.getScale(p0);
    }

    @Override
    public java.lang.String getSchemaName(int p0) throws java.sql.SQLException {
        return delegate.getSchemaName(p0);
    }

    @Override
    public java.lang.String getTableName(int p0) throws java.sql.SQLException {
        return delegate.getTableName(p0);
    }

    @Override
    public boolean isAutoIncrement(int p0) throws java.sql.SQLException {
        return delegate.isAutoIncrement(p0);
    }

    @Override
    public boolean isCaseSensitive(int p0) throws java.sql.SQLException {
        return delegate.isCaseSensitive(p0);
    }

    @Override
    public boolean isCurrency(int p0) throws java.sql.SQLException {
        return delegate.isCurrency(p0);
    }

    @Override
    public boolean isDefinitelyWritable(int p0) throws java.sql.SQLException {
        return delegate.isDefinitelyWritable(p0);
    }

    @Override
    public int isNullable(int p0) throws java.sql.SQLException {
        return delegate.isNullable(p0);
    }

    @Override
    public boolean isReadOnly(int p0) throws java.sql.SQLException {
        return delegate.isReadOnly(p0);
    }

    @Override
    public boolean isSearchable(int p0) throws java.sql.SQLException {
        return delegate.isSearchable(p0);
    }

    @Override
    public boolean isSigned(int p0) throws java.sql.SQLException {
        return delegate.isSigned(p0);
    }

    @Override
    public boolean isWritable(int p0) throws java.sql.SQLException {
        return delegate.isWritable(p0);
    }
}
