/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import java.sql.Statement;
import org.postgresql.PGStatement;
import java.sql.SQLException;

/**
 * Forwards every {@link Statement} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingStatement implements Statement, PGStatement {

    protected final Statement delegate;
    protected final PGStatement pgDelegate;

    protected ForwardingStatement(Statement delegate) throws SQLException {
        this.delegate = delegate;
        this.pgDelegate = delegate.unwrap(PGStatement.class);
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public void addBatch(java.lang.String p0) throws java.sql.SQLException {
        delegate.addBatch(p0);
    }

    @Override
    public void cancel() throws java.sql.SQLException {
        delegate.cancel();
    }

    @Override
    public void clearBatch() throws java.sql.SQLException {
        delegate.clearBatch();
    }

    @Override
    public void clearWarnings() throws java.sql.SQLException {
        delegate.clearWarnings();
    }

    @Override
    public void close() throws java.sql.SQLException {
        delegate.close();
    }

    @Override
    public void closeOnCompletion() throws java.sql.SQLException {
        delegate.closeOnCompletion();
    }

    @Override
    public java.lang.String enquoteIdentifier(java.lang.String p0, boolean p1) throws java.sql.SQLException {
        return delegate.enquoteIdentifier(p0, p1);
    }

    @Override
    public java.lang.String enquoteLiteral(java.lang.String p0) throws java.sql.SQLException {
        return delegate.enquoteLiteral(p0);
    }

    @Override
    public java.lang.String enquoteNCharLiteral(java.lang.String p0) throws java.sql.SQLException {
        return delegate.enquoteNCharLiteral(p0);
    }

    @Override
    public boolean execute(java.lang.String p0) throws java.sql.SQLException {
        return delegate.execute(p0);
    }

    @Override
    public boolean execute(java.lang.String p0, int p1) throws java.sql.SQLException {
        return delegate.execute(p0, p1);
    }

    @Override
    public boolean execute(java.lang.String p0, int[] p1) throws java.sql.SQLException {
        return delegate.execute(p0, p1);
    }

    @Override
    public boolean execute(java.lang.String p0, java.lang.String[] p1) throws java.sql.SQLException {
        return delegate.execute(p0, p1);
    }

    @Override
    public int[] executeBatch() throws java.sql.SQLException {
        return delegate.executeBatch();
    }

    @Override
    public long[] executeLargeBatch() throws java.sql.SQLException {
        return delegate.executeLargeBatch();
    }

    @Override
    public long executeLargeUpdate(java.lang.String p0) throws java.sql.SQLException {
        return delegate.executeLargeUpdate(p0);
    }

    @Override
    public long executeLargeUpdate(java.lang.String p0, int p1) throws java.sql.SQLException {
        return delegate.executeLargeUpdate(p0, p1);
    }

    @Override
    public long executeLargeUpdate(java.lang.String p0, int[] p1) throws java.sql.SQLException {
        return delegate.executeLargeUpdate(p0, p1);
    }

    @Override
    public long executeLargeUpdate(java.lang.String p0, java.lang.String[] p1) throws java.sql.SQLException {
        return delegate.executeLargeUpdate(p0, p1);
    }

    @Override
    public java.sql.ResultSet executeQuery(java.lang.String p0) throws java.sql.SQLException {
        return delegate.executeQuery(p0);
    }

    @Override
    public int executeUpdate(java.lang.String p0) throws java.sql.SQLException {
        return delegate.executeUpdate(p0);
    }

    @Override
    public int executeUpdate(java.lang.String p0, int p1) throws java.sql.SQLException {
        return delegate.executeUpdate(p0, p1);
    }

    @Override
    public int executeUpdate(java.lang.String p0, int[] p1) throws java.sql.SQLException {
        return delegate.executeUpdate(p0, p1);
    }

    @Override
    public int executeUpdate(java.lang.String p0, java.lang.String[] p1) throws java.sql.SQLException {
        return delegate.executeUpdate(p0, p1);
    }

    @Override
    public boolean getAdaptiveFetch() {
        return pgDelegate.getAdaptiveFetch();
    }

    @Override
    public java.sql.Connection getConnection() throws java.sql.SQLException {
        return delegate.getConnection();
    }

    @Override
    public int getFetchDirection() throws java.sql.SQLException {
        return delegate.getFetchDirection();
    }

    @Override
    public int getFetchSize() throws java.sql.SQLException {
        return delegate.getFetchSize();
    }

    @Override
    public java.sql.ResultSet getGeneratedKeys() throws java.sql.SQLException {
        return delegate.getGeneratedKeys();
    }

    @Override
    public long getLargeMaxRows() throws java.sql.SQLException {
        return delegate.getLargeMaxRows();
    }

    @Override
    public long getLargeUpdateCount() throws java.sql.SQLException {
        return delegate.getLargeUpdateCount();
    }

    @Override
    public long getLastOID() throws java.sql.SQLException {
        return pgDelegate.getLastOID();
    }

    @Override
    public int getMaxFieldSize() throws java.sql.SQLException {
        return delegate.getMaxFieldSize();
    }

    @Override
    public int getMaxRows() throws java.sql.SQLException {
        return delegate.getMaxRows();
    }

    @Override
    public boolean getMoreResults() throws java.sql.SQLException {
        return delegate.getMoreResults();
    }

    @Override
    public boolean getMoreResults(int p0) throws java.sql.SQLException {
        return delegate.getMoreResults(p0);
    }

    @Override
    public int getPrepareThreshold() {
        return pgDelegate.getPrepareThreshold();
    }

    @Override
    public int getQueryTimeout() throws java.sql.SQLException {
        return delegate.getQueryTimeout();
    }

    @Override
    public java.sql.ResultSet getResultSet() throws java.sql.SQLException {
        return delegate.getResultSet();
    }

    @Override
    public int getResultSetConcurrency() throws java.sql.SQLException {
        return delegate.getResultSetConcurrency();
    }

    @Override
    public int getResultSetHoldability() throws java.sql.SQLException {
        return delegate.getResultSetHoldability();
    }

    @Override
    public int getResultSetType() throws java.sql.SQLException {
        return delegate.getResultSetType();
    }

    @Override
    public int getUpdateCount() throws java.sql.SQLException {
        return delegate.getUpdateCount();
    }

    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException {
        return delegate.getWarnings();
    }

    @Override
    public boolean isCloseOnCompletion() throws java.sql.SQLException {
        return delegate.isCloseOnCompletion();
    }

    @Override
    public boolean isClosed() throws java.sql.SQLException {
        return delegate.isClosed();
    }

    @Override
    public boolean isPoolable() throws java.sql.SQLException {
        return delegate.isPoolable();
    }

    @Override
    public boolean isSimpleIdentifier(java.lang.String p0) throws java.sql.SQLException {
        return delegate.isSimpleIdentifier(p0);
    }

    @Override
    public boolean isUseServerPrepare() {
        return pgDelegate.isUseServerPrepare();
    }

    @Override
    public void setAdaptiveFetch(boolean p0) {
        pgDelegate.setAdaptiveFetch(p0);
    }

    @Override
    public void setCursorName(java.lang.String p0) throws java.sql.SQLException {
        delegate.setCursorName(p0);
    }

    @Override
    public void setEscapeProcessing(boolean p0) throws java.sql.SQLException {
        delegate.setEscapeProcessing(p0);
    }

    @Override
    public void setFetchDirection(int p0) throws java.sql.SQLException {
        delegate.setFetchDirection(p0);
    }

    @Override
    public void setFetchSize(int p0) throws java.sql.SQLException {
        delegate.setFetchSize(p0);
    }

    @Override
    public void setLargeMaxRows(long p0) throws java.sql.SQLException {
        delegate.setLargeMaxRows(p0);
    }

    @Override
    public void setMaxFieldSize(int p0) throws java.sql.SQLException {
        delegate.setMaxFieldSize(p0);
    }

    @Override
    public void setMaxRows(int p0) throws java.sql.SQLException {
        delegate.setMaxRows(p0);
    }

    @Override
    public void setPoolable(boolean p0) throws java.sql.SQLException {
        delegate.setPoolable(p0);
    }

    @Override
    public void setPrepareThreshold(int p0) throws java.sql.SQLException {
        pgDelegate.setPrepareThreshold(p0);
    }

    @Override
    public void setQueryTimeout(int p0) throws java.sql.SQLException {
        delegate.setQueryTimeout(p0);
    }

    @Override
    public void setUseServerPrepare(boolean p0) throws java.sql.SQLException {
        pgDelegate.setUseServerPrepare(p0);
    }
}
