/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */
package io.crate.client.jdbc;

import java.sql.Connection;
import org.postgresql.PGConnection;
import java.sql.SQLException;

/**
 * Forwards every {@link Connection} method to a delegate.
 * Generated by devtools/GenerateForwarding.java — do not edit by hand.
 */
@SuppressWarnings("deprecation")
public abstract class ForwardingConnection implements Connection, PGConnection {

    protected final Connection delegate;
    protected final PGConnection pgDelegate;

    protected ForwardingConnection(Connection delegate) throws SQLException {
        this.delegate = delegate;
        this.pgDelegate = delegate.unwrap(PGConnection.class);
    }

    @Override
    public <T> T unwrap(java.lang.Class<T> p0) throws java.sql.SQLException {
        return p0.isInstance(this) ? p0.cast(this) : delegate.unwrap(p0);
    }

    @Override
    public boolean isWrapperFor(java.lang.Class<?> p0) throws java.sql.SQLException {
        return p0.isInstance(this) || delegate.isWrapperFor(p0);
    }

    @Override
    public void abort(java.util.concurrent.Executor p0) throws java.sql.SQLException {
        delegate.abort(p0);
    }

    @Override
    public void addDataType(java.lang.String p0, java.lang.Class<? extends org.postgresql.util.PGobject> p1) throws java.sql.SQLException {
        pgDelegate.addDataType(p0, p1);
    }

    @Override
    public void addDataType(java.lang.String p0, java.lang.String p1) {
        pgDelegate.addDataType(p0, p1);
    }

    @Override
    public void alterUserPassword(java.lang.String p0, char[] p1, java.lang.String p2) throws java.sql.SQLException {
        pgDelegate.alterUserPassword(p0, p1, p2);
    }

    @Override
    public void beginRequest() throws java.sql.SQLException {
        delegate.beginRequest();
    }

    @Override
    public void cancelQuery() throws java.sql.SQLException {
        pgDelegate.cancelQuery();
    }

    @Override
    public void clearWarnings() throws java.sql.SQLException {
        delegate.clearWarnings();
    }

    @Override
    public void close() throws java.sql.SQLException {
        delegate.close();
    }

    @Override
    public void commit() throws java.sql.SQLException {
        delegate.commit();
    }

    @Override
    public java.sql.Array createArrayOf(java.lang.String p0, java.lang.Object[] p1) throws java.sql.SQLException {
        return delegate.createArrayOf(p0, p1);
    }

    @Override
    public java.sql.Array createArrayOf(java.lang.String p0, java.lang.Object p1) throws java.sql.SQLException {
        return pgDelegate.createArrayOf(p0, p1);
    }

    @Override
    public java.sql.Blob createBlob() throws java.sql.SQLException {
        return delegate.createBlob();
    }

    @Override
    public java.sql.Clob createClob() throws java.sql.SQLException {
        return delegate.createClob();
    }

    @Override
    public java.sql.NClob createNClob() throws java.sql.SQLException {
        return delegate.createNClob();
    }

    @Override
    public java.sql.SQLXML createSQLXML() throws java.sql.SQLException {
        return delegate.createSQLXML();
    }

    @Override
    public java.sql.Statement createStatement() throws java.sql.SQLException {
        return delegate.createStatement();
    }

    @Override
    public java.sql.Statement createStatement(int p0, int p1) throws java.sql.SQLException {
        return delegate.createStatement(p0, p1);
    }

    @Override
    public java.sql.Statement createStatement(int p0, int p1, int p2) throws java.sql.SQLException {
        return delegate.createStatement(p0, p1, p2);
    }

    @Override
    public java.sql.Struct createStruct(java.lang.String p0, java.lang.Object[] p1) throws java.sql.SQLException {
        return delegate.createStruct(p0, p1);
    }

    @Override
    public void endRequest() throws java.sql.SQLException {
        delegate.endRequest();
    }

    @Override
    public java.lang.String escapeIdentifier(java.lang.String p0) throws java.sql.SQLException {
        return pgDelegate.escapeIdentifier(p0);
    }

    @Override
    public java.lang.String escapeLiteral(java.lang.String p0) throws java.sql.SQLException {
        return pgDelegate.escapeLiteral(p0);
    }

    @Override
    public boolean getAdaptiveFetch() {
        return pgDelegate.getAdaptiveFetch();
    }

    @Override
    public boolean getAutoCommit() throws java.sql.SQLException {
        return delegate.getAutoCommit();
    }

    @Override
    public org.postgresql.jdbc.AutoSave getAutosave() {
        return pgDelegate.getAutosave();
    }

    @Override
    public int getBackendPID() {
        return pgDelegate.getBackendPID();
    }

    @Override
    public java.lang.String getCatalog() throws java.sql.SQLException {
        return delegate.getCatalog();
    }

    @Override
    public java.util.Properties getClientInfo() throws java.sql.SQLException {
        return delegate.getClientInfo();
    }

    @Override
    public java.lang.String getClientInfo(java.lang.String p0) throws java.sql.SQLException {
        return delegate.getClientInfo(p0);
    }

    @Override
    public org.postgresql.copy.CopyManager getCopyAPI() throws java.sql.SQLException {
        return pgDelegate.getCopyAPI();
    }

    @Override
    public int getDefaultFetchSize() {
        return pgDelegate.getDefaultFetchSize();
    }

    @Override
    public org.postgresql.fastpath.Fastpath getFastpathAPI() throws java.sql.SQLException {
        return pgDelegate.getFastpathAPI();
    }

    @Override
    public int getHoldability() throws java.sql.SQLException {
        return delegate.getHoldability();
    }

    @Override
    public org.postgresql.largeobject.LargeObjectManager getLargeObjectAPI() throws java.sql.SQLException {
        return pgDelegate.getLargeObjectAPI();
    }

    @Override
    public java.sql.DatabaseMetaData getMetaData() throws java.sql.SQLException {
        return delegate.getMetaData();
    }

    @Override
    public int getNetworkTimeout() throws java.sql.SQLException {
        return delegate.getNetworkTimeout();
    }

    @Override
    public org.postgresql.PGNotification[] getNotifications() throws java.sql.SQLException {
        return pgDelegate.getNotifications();
    }

    @Override
    public org.postgresql.PGNotification[] getNotifications(int p0) throws java.sql.SQLException {
        return pgDelegate.getNotifications(p0);
    }

    @Override
    public java.lang.String getParameterStatus(java.lang.String p0) {
        return pgDelegate.getParameterStatus(p0);
    }

    @Override
    public java.util.Map<java.lang.String, java.lang.String> getParameterStatuses() {
        return pgDelegate.getParameterStatuses();
    }

    @Override
    public org.postgresql.jdbc.PreferQueryMode getPreferQueryMode() {
        return pgDelegate.getPreferQueryMode();
    }

    @Override
    public int getPrepareThreshold() {
        return pgDelegate.getPrepareThreshold();
    }

    @Override
    public int getQueryTimeout() {
        return pgDelegate.getQueryTimeout();
    }

    @Override
    public org.postgresql.replication.PGReplicationConnection getReplicationAPI() {
        return pgDelegate.getReplicationAPI();
    }

    @Override
    public java.lang.String getSchema() throws java.sql.SQLException {
        return delegate.getSchema();
    }

    @Override
    public int getTransactionIsolation() throws java.sql.SQLException {
        return delegate.getTransactionIsolation();
    }

    @Override
    public java.util.Map<java.lang.String, java.lang.Class<?>> getTypeMap() throws java.sql.SQLException {
        return delegate.getTypeMap();
    }

    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException {
        return delegate.getWarnings();
    }

    @Override
    public boolean isClosed() throws java.sql.SQLException {
        return delegate.isClosed();
    }

    @Override
    public boolean isReadOnly() throws java.sql.SQLException {
        return delegate.isReadOnly();
    }

    @Override
    public boolean isValid(int p0) throws java.sql.SQLException {
        return delegate.isValid(p0);
    }

    @Override
    public java.lang.String nativeSQL(java.lang.String p0) throws java.sql.SQLException {
        return delegate.nativeSQL(p0);
    }

    @Override
    public java.sql.CallableStatement prepareCall(java.lang.String p0) throws java.sql.SQLException {
        return delegate.prepareCall(p0);
    }

    @Override
    public java.sql.CallableStatement prepareCall(java.lang.String p0, int p1, int p2) throws java.sql.SQLException {
        return delegate.prepareCall(p0, p1, p2);
    }

    @Override
    public java.sql.CallableStatement prepareCall(java.lang.String p0, int p1, int p2, int p3) throws java.sql.SQLException {
        return delegate.prepareCall(p0, p1, p2, p3);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0) throws java.sql.SQLException {
        return delegate.prepareStatement(p0);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0, int p1) throws java.sql.SQLException {
        return delegate.prepareStatement(p0, p1);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0, int[] p1) throws java.sql.SQLException {
        return delegate.prepareStatement(p0, p1);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0, java.lang.String[] p1) throws java.sql.SQLException {
        return delegate.prepareStatement(p0, p1);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0, int p1, int p2) throws java.sql.SQLException {
        return delegate.prepareStatement(p0, p1, p2);
    }

    @Override
    public java.sql.PreparedStatement prepareStatement(java.lang.String p0, int p1, int p2, int p3) throws java.sql.SQLException {
        return delegate.prepareStatement(p0, p1, p2, p3);
    }

    @Override
    public void releaseSavepoint(java.sql.Savepoint p0) throws java.sql.SQLException {
        delegate.releaseSavepoint(p0);
    }

    @Override
    public void rollback() throws java.sql.SQLException {
        delegate.rollback();
    }

    @Override
    public void rollback(java.sql.Savepoint p0) throws java.sql.SQLException {
        delegate.rollback(p0);
    }

    @Override
    public void setAdaptiveFetch(boolean p0) {
        pgDelegate.setAdaptiveFetch(p0);
    }

    @Override
    public void setAutoCommit(boolean p0) throws java.sql.SQLException {
        delegate.setAutoCommit(p0);
    }

    @Override
    public void setAutosave(org.postgresql.jdbc.AutoSave p0) {
        pgDelegate.setAutosave(p0);
    }

    @Override
    public void setCatalog(java.lang.String p0) throws java.sql.SQLException {
        delegate.setCatalog(p0);
    }

    @Override
    public void setClientInfo(java.util.Properties p0) throws java.sql.SQLClientInfoException {
        delegate.setClientInfo(p0);
    }

    @Override
    public void setClientInfo(java.lang.String p0, java.lang.String p1) throws java.sql.SQLClientInfoException {
        delegate.setClientInfo(p0, p1);
    }

    @Override
    public void setDefaultFetchSize(int p0) throws java.sql.SQLException {
        pgDelegate.setDefaultFetchSize(p0);
    }

    @Override
    public void setHoldability(int p0) throws java.sql.SQLException {
        delegate.setHoldability(p0);
    }

    @Override
    public void setNetworkTimeout(java.util.concurrent.Executor p0, int p1) throws java.sql.SQLException {
        delegate.setNetworkTimeout(p0, p1);
    }

    @Override
    public void setPrepareThreshold(int p0) {
        pgDelegate.setPrepareThreshold(p0);
    }

    @Override
    public void setQueryTimeout(int p0) throws java.sql.SQLException {
        pgDelegate.setQueryTimeout(p0);
    }

    @Override
    public void setReadOnly(boolean p0) throws java.sql.SQLException {
        delegate.setReadOnly(p0);
    }

    @Override
    public java.sql.Savepoint setSavepoint() throws java.sql.SQLException {
        return delegate.setSavepoint();
    }

    @Override
    public java.sql.Savepoint setSavepoint(java.lang.String p0) throws java.sql.SQLException {
        return delegate.setSavepoint(p0);
    }

    @Override
    public void setSchema(java.lang.String p0) throws java.sql.SQLException {
        delegate.setSchema(p0);
    }

    @Override
    public void setShardingKey(java.sql.ShardingKey p0) throws java.sql.SQLException {
        delegate.setShardingKey(p0);
    }

    @Override
    public void setShardingKey(java.sql.ShardingKey p0, java.sql.ShardingKey p1) throws java.sql.SQLException {
        delegate.setShardingKey(p0, p1);
    }

    @Override
    public boolean setShardingKeyIfValid(java.sql.ShardingKey p0, int p1) throws java.sql.SQLException {
        return delegate.setShardingKeyIfValid(p0, p1);
    }

    @Override
    public boolean setShardingKeyIfValid(java.sql.ShardingKey p0, java.sql.ShardingKey p1, int p2) throws java.sql.SQLException {
        return delegate.setShardingKeyIfValid(p0, p1, p2);
    }

    @Override
    public void setTransactionIsolation(int p0) throws java.sql.SQLException {
        delegate.setTransactionIsolation(p0);
    }

    @Override
    public void setTypeMap(java.util.Map<java.lang.String, java.lang.Class<?>> p0) throws java.sql.SQLException {
        delegate.setTypeMap(p0);
    }
}
